### ISSUE TITLE
Use hashed passwords in settings.json

### ISSUE THREAD

**Issue by disy-mk** [ether/etherpad-lite#1650]
Would be nice to use hashed passes there; maybe an additional JS tool (in ./tools) to create hashed pwds. Maybe the tool could even handle "account creation" for /admin, i.e. ask for user, pass and if is_admin.

**Comment by JohnMcLear** [comment]
Solved by https://www.npmjs.org/package/ep_hash_auth

**Comment by freddymartinez9** [comment]
I don't think this is quite resolved, namely because the plugin doesn't seem to work quite as expected. For example, the installer warns about a pluingw mismatch between node_modules/async as an unmet dependency (using the lastest build of etherpad).   I manually created a "users": { "username" : { "hash" : {"hash_value", "is_admin: false,} entry and whenever i try to login it just spins on login (i.e. no password reject for being wrong, no connection timeout and no feedback to the end user).  I *can* login using the unhashed usernames so i don't know if the problem is in the settings.json. 

Thoughts? @LaKing ?

**Comment by LaKing** [comment]
Your syntax seems to be wrong.
```
 "users": {
    "Bud": {"hash": "6c98..66d2","is_admin": true},
    "Al":  {"hash": "c7r2..b72c","is_admin": true}
  }
```

**Comment by muxator** [comment]
For **1.7** (the upcoming release) we cannot do much more than mentioning `ep_hash_auth` in the documentation (BTW, in its current form it has some usability issues: see https://github.com/LaKing/ep_hash_auth/issues/2).

It could be mainlined, provided the original author allows it, the code is polished, usability problems are overcome...

**Comment by Wikinaut** [comment]
@muxator as far as I remember, I had no installation problems ( https://github.com/LaKing/ep_hash_auth/issues/2 ) any more (running debian 10 aka buster/sid).

**Comment by muxator** [comment]
Thanks, @Laking, I understand.
Since `ep_hash_auth` is a good starting point, I have opened https://github.com/LaKing/ep_hash_auth/issues/4.

Please tell me what you think about it. Thanks again!

**Comment by muxator** [comment]
Thanks to @Laking generosity, this ticket is replaced by #3463.
