### ISSUE TITLE
ERROR: module at "ep_etherpad-lite/static/js/colorutils" does not exist

### ISSUE THREAD

**Issue by offerman** [ether/etherpad-lite#1856]
After installation, when creating and entering a new (i.e. the first) pad, I get the following message:

An error occured while loading the pad
Error: The module at "ep_etherpad-lite/static/js/colorutils" does not exist. in https://etherpad-lite.********.com:9001/static/js/require-kernel.js (line 569)

**Comment by bcorrero** [comment]
Is there any way to have Etherpad automatically refresh/delete the cache as needed?

I am getting the same error after running Etherpad as a service for a few hours.  I get this exact initial error once and then after that it returns a simple "connection refused" error.  Because of this, we simply cannot leave it running on the server since it crashes after a few hours.  This would require multi-daily restarts of the service which defeats the entire purpose of having it permanently running on a server.

An error occured while loading the pad
Uncaught Error: The module at "ep_etherpad-lite/static/js/colorutils" 
does not exist. in http://10.94.105.236:9001/static/js/require-kernel.js 
(line 596)

Brian
