### ISSUE TITLE
Ultra feature request: make etherpad-lite offline-capable (HTML5)

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#190]
In the mid-term, I am very interested to have a version which survives interruptions of the internet connection and uses the local storage (i.e. HTML5).

Of course, with the view to the simultaneous editing property, resuming work under multi-users conditions will only be reasonible possible if the "client-site saved" edits (offline-edits) can be merged with the others edits without conflicts, for example, if the edits were in different sections of the pad.

Perhaps, this is not an easy task.

[UPDATED after this bug has been closed]
This is an important feature, and a must have, if you are editing while travelling in an Intercity train, and when the internet connection is interrupted when in a tunnel, or another reason.

**Comment by 2xyo** [comment]
:+1: for this feature

**Comment by JohnMcLear** [comment]
@2xyo it's doable but we need someone to sponsor the development, hopefully a sponsor will come forward and then we can make it a reality :)

**Comment by jreus** [comment]
Even when collaboratively editing not in a train - even in the same room on a local server - there can be connection issues. The biggest problem I encounter is often losing work/notes due to a connection disruption, or regular connection disruptions. The robustness of offline editing is the only reason I use google docs.. would love to switch over to etherpad 100%! :-)

**Comment by chagai95** [comment]
Why was this closed? 🙈
