### ISSUE TITLE
A setting to specify the url prefix of the installation

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#2025]
- No more confusing relative paths
- plugins can use the setting to build the correct urls, too

(_Asked for over here: https://groups.google.com/forum/#!msg/etherpad-lite-dev/l6tSr1Y75ZI/GSMzMIctPOkJ_)

**Comment by JohnMcLear** [comment]
Is this actually a problem?

**Comment by gabrielliwerant** [comment]
Not sure if this is the same issue, but etherpad seems to require being in a top level directory. If etherpad is installed in a subdirectory, such as `applications/libs/etherpad`, the server cannot locate the `settings.json` file. Moving the settings file does not work because this confuses the database directory...

This is less than ideal. I'm working on another project in git and I'd like to share a modified settings file with other coders. Under this arrangement, I cannot do this in my existing project. It should be possible to treat etherpad as a part of another application for source control and development purposes, but etherpad does not seem to be set up this way.

**Comment by gabrielliwerant** [comment]
Possible mitigation for this issue: https://github.com/ether/etherpad-lite/pull/2477

**Comment by llaurent** [comment]
If this feature request is about a new path option to make it work on http://host:port/path/ instead of http://host:port/ I'm all for it ! :-)
That would make reverse far more simpler when you don't want to use a dedicated vhost...

**Comment by flotho** [comment]
@llaurent, I'm also struggling with making it work under subdirectory

**Comment by JohnMcLear** [comment]
Is this still an issue?  Afaik it is not...
