### ISSUE TITLE
Git as a backend?

### ISSUE THREAD

**Issue by jmatsushita** [ether/etherpad-lite#2106]
Hi,

Would it be possible to use git or github as a backend storage for etherpad? This would allow for instance to provide an alternative to software such as prose.io @prose which uses github as a storage backend and works in combination with Jekyll to generate static sites. Substance.io @substance @michael is also to some extent looking at this. 

If some documents could be both collaboratively edited in real-time as well as be ready for open collaboration on an open git repository (and even published/released on websites at specific moments), it seems we would have a nice and lightweight real-time collaborative cms...

This could possibly be implemented in conjunction with the existing github plugin to allow collaborators to have their github identities associated to their edits (possibly allowing a default/anonymous account to be configured to allow anonymous edits if desired), markdownify to allow inline formatting using markdown, fileupload/previewimage to attach images, maybe table_of_contents to allow navigation in large documents.

Clicking on the Star icon "Save Revision" would "flatten" the contributor's edits and apply them as attributed diffs/patches (probably some interesting problems with bundling operational transforms...).

Cheers,

Jun

**Comment by JohnMcLear** [comment]
Closing this due to lack of sanity.

**Comment by xloem** [comment]
@JohnMcLear would you be willing to re-open this issue and simply tag it help-wanted?  The benefits would be so profound.

**Comment by JohnMcLear** [comment]
@xloem wouldn't this be a consideration for UeberDB2 ?  We abstract our database stuff through UeberDB so..

**Comment by xloem** [comment]
@JohnMcLear what you describe opposes @marcelklehr 's suggestion from 2014 above.  I'll take your advice as more informed, being so much more recent.

**Comment by JohnMcLear** [comment]
Mheh, fine, will re-open and flag as plugin request.  If you want to contribute I can do the client side logic for handling click events etc.

**Comment by JohnMcLear** [comment]
@xloem I spent an hour on this and came up with a prototype: https://mclear.co.uk/2020/04/25/automatically-storing-etherpad-pad-contents-in-git/

It stores the entire database file in .git, it isn't author aware.  This shows a concept anyway, tighter integration is doable but requires work.

**Comment by muxator** [comment]
@JohnMcLear, what I'd be satisfied with is simply the possibility of committing specific versions to source control. No problem in losing the granularity of the single edit authorship, since that is weel tracked by Etherpad already. Something on the lines of:

1. the user opens pad `/p/test`
2. the user saves a revision with the star icon
3. a dialog with a commit message is opened
4. the current version of the pad is exported in some form (let's say text for now)
5. the exported pad contents is committed to the repo as `<BASE>/test.txt`. The user's commit message is appended with the revision version number

If you think about it, the base functionality is not even something specifically bound to a version control system. What the plugin needs to do is to trigger a custom shell command when a revision is saved.

It would be compatible with other workflows (committing to mercurial/git, sending via email, triggering backups, ...).

**Comment by JohnMcLear** [comment]
Okay thanks for being specific about requirements..

So what you could do is have a plugin that has the following functionality..

 - [ ] On save revision msg writes txt file to location on server
 - [ ] On save revision button press user is presented a popup asking them to provide commit message data.
 - [ ] On commit message data commit the text file to the server with the commit message data.

So dev steps.
 - [ ] Create popup input (ref ep_mathjax for best method).
 - [ ] Handle the communication (ref ep_set_pad_title)
 - [ ] Handle the writing of the file (let's say it's var/git/padId.txt for simplicity)

The admin would need to 
 - [ ] ``mkdir ETHERPAD_BASE/var/git && git init ETHERPAD_BASE/var/git``

RE other workflows, I don't see how, because if you want a message you have to specify how that message will be delivered to the backend..  IE in the git example it's a git commit -m '$foo'..  You would need to replace that logic which because settings.json doesn't allow functions being inserted how would this work?

**Comment by muxator** [comment]
**Configuration parameters** for the plugin:

1. **`REPO_PATH`**: path where the repository is going to be created. I do not know is going with `ETHERPAD_BASE/var/git` is a good start, since this is something that the administrator may want to have fine grained control over, plus that would be a git repo inside another git repo.

2. **`INIT_COMMAND`**. Support some form of keyword syntax. For example the one we have in `settings.json`.
   Default value:
   ```
   git init "${REPO_PATH}"
   ```

3. **`SAVE_COMMAND`**.
   Default:
   ```
   git -C "${REPO_PATH} add <PADNAME.txt> && git -C "${REPO_PATH}" commit -m "${COMMIT_MESSAGE}"
   ```

This would be admin friendly.
As side effect, it could be adapted to other workflows.

**Comment by JohnMcLear** [comment]
Dumb question..  Sorry!

If I settings I have the string..

```
  "ep_git_commit_saved_revision":{
    "path":"/home/jose/develop/var/git",
    "initCommand":"git init ${path}",  <---------- this string
    "saveCommand":"git -C \"${path} add ${padId} && git -C \"${path}\" commit -m \"${message}\""
  }
```

I want to use ${path} here as a variable.. So I do..

```
var path = settings.ep_git_commit_saved_revision.path;
console.warn(initCommand);
```

I want this to output git init /home/jose/develop/var/git

What's the best way to achieve this?

**Comment by JohnMcLear** [comment]
Test with ``npm install ep_git_commit_saved_revision``

and copy this into ``settings.json``

```
  /*
    Available variables to plugin are:
    * padId = The ID of the Pad you are working on IE "foo"
    * message = the message IE "Hello world"
    * path = The path defined in the settings blob
  */
  "ep_git_commit_saved_revision":{
    "path":"/home/jose/develop/var/git",
    "initCommand":"git init ${path}",
    "saveCommand":"git -C \"${path}\" add \"${padId}.txt\" && git -C \"${path}\" commit -m \"${message}\""
  }

```

Whoever wants to help maintain the plugin feel free, the bulk of the work is done...

**Comment by JohnMcLear** [comment]
Closing as I gave enough time to a feature request 👯‍♂️
