### ISSUE TITLE
defaultpadtext

### ISSUE THREAD

**Issue by spiffomatic64** [ether/etherpad-lite#2156]
Is there a way to include formatting into the defaultpadtext? (sorry if this is already possible and I just missed it)

But it would be nice to include either html or some other formatting language to bold/center/change colors/etc into the defaultpadtext of a new pad

**Comment by JohnMcLear** [comment]
This should now be doable if you use the API to create a new Pad..  Use the setHTML method.

Let us know if this isn't working and we can re-open, thanks!

**Comment by zhenkuncua** [comment]
Hi, 

  I tried the setHTML method but it strips off all the attributes in the HTML string.

  I then tried calling setHTML with the results I got from getHTML (after entering a link in the pad) thinking that some special escaping might be needed, but the entire link was removed instead after the call.

Thanks.

**Comment by zhenkuncua** [comment]
Hi, 
  setHTML strips off all node attributes, and breaks when called with the result of getHTML 
  I think this is because it is based on a ChangeSet approach, and the changeSet result is just an encoded set of actions applied to the actual text.  
 Given this, is it really possible to set the initial HTML data?

Thanks.
