### ISSUE TITLE
Newlines insertion in between an ordered list reset numbering

### ISSUE THREAD

**Issue by miaocanada** [ether/etherpad-lite#2194]
When a user is trying to insert newlines in between an ordered list(list with numbers), the number in the list starting from the position in which newlines are inserted will be changed to "1". Details below:

1.Type 4 lines of text, and make them as ordered list.
2.Position the cursor at the end of line 2. Press Enter.
3.Now it shows “3.” before the cursor. Press backspace.
![screenshot from 2014-07-08 12 17 34_c](https://cloud.githubusercontent.com/assets/7980264/3515397/63773736-06d5-11e4-92e8-7e7d29ed6241.png)

4.Now next line supposes to be “3.”, but it changes to “1.” The following number should be “4.” but instead “2.”
![screenshot from 2014-07-08 12 17 44_c](https://cloud.githubusercontent.com/assets/7980264/3515337/de00356c-06d4-11e4-954f-ac696e389d19.png)

So Etherpad will treat the insertion as breaking the whole list into separate lists. This behaviour is different from LibreOffice Writer, and Microsoft Word.

Expected newlines inserted should not break the ordered list into separate lists, i.e. Etherpad should keep the consecutive numbers even with newlines in between the ordered list. This is useful when collaborators are making questionnaires or creating exams.

**Comment by martinvonwittich** [comment]
Would it be possible to add a special key combination like Shift+Return that inserts empty lines without resetting the numbering? For example, when you have the following list:

```
1. foo
2. bar
3. foobar
4. barfoo
```
and someone points the cursor behind "2. bar" and presses Return, the list should be split up in two separate lists (as it currently does):

```
1. foo
2. bar

1. foobar
2. barfoo
```
But when the user presses Shift+Return, it should insert an empty line without splitting the list:

```
1. foo
2. bar

3. foobar
4. barfoo
```

That way no heuristics would need any changing, and the default behaviour wouldn't change. Also, any text inserted between the list elements shold be indented, like this:

```
1. foo
2. bar

   foobarfoo

3. foobar
4. barfoo
```

**Comment by JohnMcLear** [comment]
I thought a lot about this and the short answer is no.  This is because the contentcollector is also used for import.  So you can't have exceptions for none standards.

So you can have:

```
1. hello

1. world
```
and
```
1. hello
cruel
2. world
```
or
```
1. hello

2. world
```

You have to be explicit on if empty line breaks reset the counter or not.  What you can do is indent a line so..

```
1. hello
%tabbedline%
2. world
```
and

```
1. hello
cruel
2. world
```

But simply put, if you import a document with an empty line you have to be explicit about if that empty line contributes as "space" or not..

IMHO completely outdented empty lines should restart the ordered list start.

IMHO hitting enter twice should completely outdent a ordered list.
 - [x] So first enter, create new line at same indentation
 - [ ] Second enter, check previous enter has no text content and is list item
 - [ ] If so, outdent line to 0 and remove ordered list.

**Comment by JohnMcLear** [comment]
I fixed OLs a lot recently and decided that this request is out of scope.
