### ISSUE TITLE
can not paste images from clipboard

### ISSUE THREAD

**Issue by GeorgeXc** [ether/etherpad-lite#2227]
when i paste an image from clipboard. the image will be soon disappeared。

**Comment by dandv** [comment]
@JohnMcLear: is it challenging to paste an image from the clipboard into Etherpad because of its collaborative nature, or into any WYSIWYG editor, period, although Imgur, Slack, GitHub, Google Docs, StackExchange and others do just that?

I'm [comparing WYSIWYG editors](https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md) and have been looking for this feature.

**Comment by JohnMcLear** [comment]
See the plugin that enables this requirement
----- Reply message -----
