### ISSUE TITLE
Etherpad password only secured pads stores the specific pad password in plain-text cookies

### ISSUE THREAD

**Issue by jaseg** [ether/etherpad-lite#230]
From a security point of view this is bad. A cookie should not contain more than a session id or a (limited-time) token. The current behavior e.g. leaks an user's password with each XSS flaw.

**Comment by JohnMcLear** [comment]
FWIW you shouldn't use pad level passwords, your access should be done by session management.  That's why this hasn't been actioned..

**Comment by JedMeister** [comment]
@muxator - sorry to be a pain, but browsing the issue tracker I found this one which IMO should be tagged `security`. FWIW I haven't tested to confirm it's still valid, so perhaps it's been addressed already and just needs to be closed?

**Comment by muxator** [comment]
Yeah, needs confirmation. Labeling for now.

**Comment by JohnMcLear** [comment]
The logic is still in to set a password and to ask for a password but I have no idea how to make it ask..  Any idea how to use that functionality?

**Comment by muxator** [comment]
Preamble: **I still did not** took the time to **replicate this**. I may be wrong.

> @muxator thoughts on dropping setPassword in the API then we can close this off?

Two alternatives. I am 55% for number **1**.

1. That's a **breaking change** for sure. In general I would be **against** it.

   If something is out in the wild and used this (borked?) functionality, we should try to **un-bork** it.
  From what I read in the thread **a way** must **exist**. It's about using an ephemeral session instead of a plaintext cookie after all...

2. if we really decide to drop this off it is because it's less work. It may make sense because we don't have such a big user base after all.
   At that point I ask: is removing the API endpoint the only thing we should do? Would exist any other redundant logic at that point that should be removed, too? If we want to remove something, **let's get rid of everything related**.

**Comment by JohnMcLear** [comment]
+1 #2

I doubt anyone is using the ``setPassword``.  99% of consuming API will be creating sessions and handling auth off pad.  I am not worried about just ripping it out, it could be a plugin if people want it?

+1 remove other redundant conversations.

**Comment by JohnMcLear** [comment]
I'm gonna document what needs doing and then make a bounty as I won't have time to complete this work before I sign off.

**Comment by JohnMcLear** [comment]
Well that was easy, took 5mins.  https://github.com/ether/etherpad-lite/pull/4178
