### ISSUE TITLE
"TypeError: type is null" on pasting

### ISSUE THREAD

**Issue by lid2000** [ether/etherpad-lite#2448]
I am having some trouble pasting text from other browser windows. Most of the time it works fine, however it seems like if a "share" widget is part of the text selection then when pasting, I get `TypeError: type is null` and the text is pasted, but no highlighting occurs and it does not save to the pad. An example would be if you were to copy/paste the text (ensuring the Share bit is selected) in [this news article] (https://au.news.yahoo.com/thewest/regional/north-west/a/25924481/airport-solar-power-plan/).

If I use Firebug to delete all the `<li>` tags in the `<ul class="share-tools-share-items">` list then copy/paste works. I've tried deleting all but one list item and removing all the attributes from it but it still errors. I think maybe the browser is trying to copy associated events and triggering them when pasting happens, but I don't have the knowledge to be able to dig further.

I can replicate this in both Chrome and Firefox, running both Windows 7 64 and on OS X 10.10.

**Comment by JohnMcLear** [comment]
Please provide some example HTML we can use as a reference.  Thanks!

**Comment by lid2000** [comment]
I linked to it in the initial comment, but
https://au.news.yahoo.com/thewest/regional/north-west/a/25924481/airport-solar-power-plan/

**Comment by lid2000** [comment]
Another example would be to go to the [Etherpad homepage] (
http://etherpad.org/), hit `Ctrl+A` to select everything then paste it in
Etherpad. I would expect the text of the page to be pasted in, however it
generates an error. I'll try and come up with a minimal test case but I
don't know how long that will take as I'm not really sure what is causing
this.

**Comment by lid2000** [comment]
Another example would be to go to the [Etherpad homepage] (http://etherpad.org/), hit `Ctrl+A` to select everything then paste it in Etherpad. I would expect the text of the page to be pasted in, however it generates an error. I'll try and come up with a minimal test case but I don't know how long that will take as I'm not really sure what is causing this.

**Comment by lid2000** [comment]
It's lists. Pasting in an unordered list from anywhere causes the error. Ordered lists seem to work fine, but 

`<ul>
<li>blah</li>
</ul>`

will make it break.

**Comment by webzwo0i** [comment]
seems to be my list code again :( will look into this

**Comment by JohnMcLear** [comment]
Thanks @webzwo0i  =)

**Comment by JohnMcLear** [comment]
fwiw we can't do test coverage of paste events :(

**Comment by webzwo0i** [comment]
do you know if an ul without a class should be indented or bullet style?

**Comment by JohnMcLear** [comment]
bullet

**Comment by webzwo0i** [comment]
OK. I tried with an empty site and <ul><li>test</li></ul> and firefox chooses bullet, so I think this makes sense. Regarding paste events: I have a small PoC at https://github.com/webzwo0i/ep-debug-helper/blob/master/selenium-paste-poc.rb and it seems, that if I directly use selenium I benefit from trusted events. I copied the thanks-list from etherpad.org ("Many individuals, companies and organizations have...") into a new pad and run my script and it pastes the whole list again. As far as I understand we use travis and saucelabs, and saucelabs does selenium. So alongside our mocha-tests, maybe we can call selenium directly on saucelabs and implement some tests (key events, pastes, caret) as dedicated selenium tests? In my setup I have only firefox right now.

My patch for the bug here is at https://github.com/ether/etherpad-lite/pull/2449 
plz test

**Comment by JohnMcLear** [comment]
Yea I think having some copy/paste direct selenium tests makes sense, at the moment we use a javascript wrapper so we can write tests in JS.  I'd like to keep the tests written that way so it's easier for people to write tests but certainly having some direct selenium tests makes sense!

**Comment by JohnMcLear** [comment]
@lid2000 I pulled to develop, let us know if it works :)

**Comment by lid2000** [comment]
Yep, looks like it's working. Thanks!
