### ISSUE TITLE
Auth was never applied to a session.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2454]
Causes EP to crash, unable to replicate reliably ;\

```
[2015-01-12 09:09:18.324] [ERROR] console - Auth was never applied to a session.  If you are using the stress-test tool then restart Etherpad and the Stress test tool.
[2015-01-12 09:09:18.327] [ERROR] console - TypeError: Cannot set property 'colorId' of null
    at /home/jose/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:317:41
    at fn (/home/jose/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:525:34)
    at /home/jose/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:449:34
    at process._tickDomainCallback (node.js:463:13)
```

**Comment by webzwo0i** [comment]
I can reproduce at least one case where this happens:
Without sending CLIENT_READY send something like 4:::{"padId":"lala","sessionID":"lala","token":"lala","password":"lala","type":"COLLABROOM","component":"pad","data":{"type":"USERINFO_UPDATE","userInfo":{"userId":"blabla","ip":"127.0.0.1","colorId":"#ec1da9","userAgent":"Anonymous"}}}

notice USERINFO_UPDATE should always come after CLIENT_READY but it bypasses the check in SocketIORouter.js:90 (because all fields are present in the message).

Because there is no valid session, there is no valid author in PadMessageHandler.js:532 and the database query returns "null" in CacheAndBufferLayer.js:294 but the result is accessed as if it was a real object in CacheAndBufferLayer:317 (e.g. null['colorId']) - that is why it's crashing.

Not 100% sure, but maybe we should change PadMessageHandler.js:260 to "return" instead of "callback()"? Would this make sense?

**Comment by JohnMcLear** [comment]
Yea this makes sense, can you make the change and hit the server with some tests to see if it still errors?

**Comment by webzwo0i** [comment]
backend and frontend tests all pass with "return" instead of "callback()", but actually I cannot test my script which causes epl to crash against 1.5, because I haven't figured out how to talk to socket.io yet. (it changed a little bit since 1.4)
however this bug was also there in 1.4 and when I test there with the change in place the bug is gone.

**Comment by JohnMcLear** [comment]
Yea so it should exist, I can test some other edge tests once it's merged.

**Comment by JohnMcLear** [comment]
@webzwo0i where you able to get this fix in?

**Comment by webzwo0i** [comment]
net yet :(
will try tonight

**Comment by webzwo0i** [comment]
I still have problems getting the "bad USER_INFO" to apply in 1.5. (message gets dropped in engine.io because there is no valid session, which is good but it prevents the bug from happening)
Will try to find other messages that could trigger it

**Comment by webzwo0i** [comment]
wow, debug time/changed-lines-of-code ratio here is pure madness...
I do have a small script now that produce the same stack trace as above against 1.5 and it is the same bug as above. plz pull

**Comment by JohnMcLear** [comment]
@webzwo0i can this be closed buddy?

**Comment by webzwo0i** [comment]
yes :)

**Comment by JohnMcLear** [comment]
Thanks!
