### ISSUE TITLE
getLineHTMLForExport produces multiple copies of a line

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2486]
If you have ep_headings2 and ep_align installed multiple copies of that line will be exported in the HTML.

To replicate install both plugins, set the attribute on both lines.  Hit up the /export/html endpoint.

What happens:  You get 2 lines of the same contents
What should happen: You get 1 line with both stylings applied.

Here is some example HTML

```
<body>
*<span style='font-size:16px'>Welcome to Etherpad!</span>  
<h2>Welcome to Etherpad!</h2>  
<div style="width:100%;margin:0 auto;list-style-position:inside;text-align:right">*<fs16>Welcome to Etherpad!</fs16></div>
</body>
</html>
```

https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js#L414 is the offending hook.

**Comment by JohnMcLear** [comment]
I created a new hook to solve this problem.

https://github.com/ether/etherpad-lite/pull/2487

The only caveat here is that the old hook set a variable and didn't append a ``<br>`` if it was used.  This new hook doesn't do that so I'm not sure what problem this solves..

**Comment by rugk** [comment]
So this issue seems to happen again...

**Comment by rugk** [comment]
It also happens with [`ep_mediawiki`](https://github.com/johnmclear/ep_mediawiki) instead of `ep_align`. In https://github.com/ether/etherpad-lite/issues/2981 I had installed both however...

**Comment by ilmartyrk** [comment]
Had a look inside the code and found why this issue is accuring. The fix is quite simple, but most of the plugins will need a little update also.
in https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js#L454

as `getLineHTMLForExport ` stacks all the return values we get a new line from each plugin that returns a value from it and it is handeled as if something is returned from getLineHTMLForExport then add it instead of the original lineContent. But as each of the plugins gets in the context param as a original value and it's not altered then we get these multiple lines each differing from another in some way.
To really make it work in every ep_ plugin it should set `context.lineContent = 'whatever you change on the line'` and return true if anything was changed  and in  the ExportHtml.js use 
`if (lineContentFromHook)
      {
        pieces.push(context.lineContent, '');
      }
      else
      {
        pieces.push(lineContent, '<br>');
      }`  instead og
`
if (lineContentFromHook)
      {
        pieces.push(lineContentFromHook, '');
      }
      else
      {
        pieces.push(lineContent, '<br>');
      }
`

**Comment by lpagliari** [comment]
Hum, that is *awesome news*, @ilmartyrk ! I remember having some issues with HTML exporting in the past, it was still not 100% depending on which plugins we had installed.

Here's part of the code that tried to work around part of those issues, on ep_font_color: https://github.com/JohnMcLear/ep_font_color/blob/master/exportHTML.js#L40-L54

One more thing that I remember about exporting: if your Etherpad instance does not have any plugin that returns any value on `getLineHTMLForExport`, the value set on `context.lineContent` was not being exported. But your suggestion seems to be addressing that, right? ("every ep_ plugin should set context.lineContent (...) and return true if anything was changed")

**Comment by ilmartyrk** [comment]
@lpagliari your work around was quite close and it helped me a little as it was one of the plugins my etherpad setup is using. But as https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js expects something back from the  `getLineHTMLForExport` hooks then yeah it didn't work before. 

Actually I was about to drop this check and instead:
`if (lineContentFromHook)
      {
        pieces.push(lineContentFromHook, '');
      }
      else
      {
        pieces.push(lineContent, '<br>');
      }` use: `pieces.push(lineContentFromHook, '');` But then I understood that this `<br>` is used to break line if lineContent is just plain text. I also thought about iterating through the concatenated result string in lineContentFromHook, so that it would work with all the existing plugins without changing any of them, but then there might be some corner cases where it's hard to estimate what code should go where in the final result
