### ISSUE TITLE
Consider MySQL UTF8 issues

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2516]
MySQL might be better with a character-set of utf8mb4 and a collation of utf8mb4_bin.

I'm not an expert in this though so we need some validation..

The reason for this encoding type is that utf8_bin lies, it can't store all utf8 encoded characters that are available in the utf8 charset.

Reference:
- http://mzsanford.com/blog/mysql-and-unicode/
- http://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5

We need opinions on this from people who have ample MySQL and character encoding experience.

**Comment by webzwo0i** [comment]
No expert but debug session revealed this to be the root cause for some crashes and inconsistencies in the database. With utf8 (as limited by https://tools.ietf.org/html/rfc3629) up to 4 of 1 byte long units are allowed. This synchronizes the expressible range with UTF-16, so Unicode code points up to U+10FFFF can be encoded. utf8mb4 is the MySQL name for this.

I migrated one installation:
The installation was at latin1(!!)... Can try this on beta if desired because our installation is really small and the used languages/features are not as diverse as it may be the case in other installations.

what I did:
stop etherpad
stop the db
cp -ab /var/lib/mysql mysql.bak
start the db
mysqlcheck -c -u user -p database-name #should return ok
mysql> alter database `database-name` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin;
mysql> alter table `store` convert to character set utf8mb4 collate utf8mb4_bin;
mysql> alter table `store` change `key` `key` varchar(100) character set utf8mb4 collate utf8mb4_bin;
mysql> alter table `store` change `value` `value` longtext character set utf8mb4 collate utf8mb4_bin;

Somewhere in the internets I found that this method would not work and you have to manually convert to varbinary/longblob and than back to varchar/longtext.
For me this was not needed (hopefully ;)) and besides I could not find a good explanation why these additional steps are needed.

SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
stop the db
open /etc/mysql/my.cnf
in section [mysql]:
default-character-set=utf8mb4

in section [mysqld]:
init_connect ='SET NAMES utf8mb4'
init_connect ='SET collation_connection = utf8mb4_bin'
character-set-server=utf8mb4
collation-server=utf8mb4_bin

Note that if you use your MySQL to host multiple databases you probably do not want to do this. Your other databases may not like it.

start the db
mysqlcheck -c -u user -p database-name #should return ok
mysql -u user -p -e "show variables where Variable_name like 'character_set%' or Variable_name like 'collation%';" dbname

Everything (except filesystem) should be utf8mb4/utf8mb4_bin by now.

A good overview of broken raw pads (without entries from plugins etc) is bin/checkPad.js so try something like:
```mysql -u user -p -e 'select `key` from `store` where `key` like "pad:%:revs:1";'|sed -e 's/:revs:[0-9]*$//g'|sed -e 's/^pad://g'|xargs -L1 node ./bin/checkPad.js```

At my installation only the pads that I had used for testing failed

What needs to be done:
* change ueberDB to create all new databases with utf8mb4
* update the tutorial at https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL
* rewrite tests to include unicode code points above U+FFFF
* run the tests with and without caching (without db round trips we actually test how well javascript deals with our chars internally)
* implement a small check at the startup of epl that checks if we support all unicode planes. If we don't do this we'd need to implement filter everywhere chars are written to db. This would include all plugins and several places in the code base.
* even with this check in place we probably encounter some crashes in the future due to more ppl using emojis etc and I already have some, will issue some PR for them.
* probably we would benefit if we POST to js-error in case checkrep fails on client-side

As a side note:
Javascript strings (and http://www.w3.org/TR/DOM-Level-3-Core/core.html#DOMString ) are UTF-16. This means they consist of two units, 16 bytes each. This affects the behaviour of epl, because we rely on things like string length. The string length of every UTF-16 pair is two! You can see the result e.g. when you insert a Unicode above U+FFFF (like 𝌂) and hit backspace. Only the last pair ("low surrogate") is removed. Thats why we need to adapt our test cases.

**Comment by webzwo0i** [comment]
Another problem that will arise:
After updating those pads that used the code points we could not express in the past will most likely make problems. They probably have two or four "?" in the atext and changesets, respectively. I could think of a skript to try to migrate the changesets automagically if checkPad fails and delete/rebuild the atexts but on the other hand this is very invasive and people might feel more save if they do a export, reimport and fix the ? by hand

**Comment by JohnMcLear** [comment]
Is it possible to fix this without modifying /etc/mysql/my.cnf ?  Those modifications seem like overkill no?

**Comment by webzwo0i** [comment]
Yes, my first test seems to indicate they are not needed (because we alter the encoding after creating the db/tables anyways). However, ueberDB must set the connection/client [0]. Otherwise the db would treat the "real utf8" we send from epl as 3-byte utf8 and then reencode it to fit into the utf8mb4 tables. This is wrong.
A quick hack for me was:
```
db.query("set names utf8mb4 collate utf8mb4_bin",null,function(err)
{
  if(err){
    throw err;
  }
});
```
in ueberDB/mysql.js' init-function. 
The problem is that in ueberDB the query-function is not exposed and thus we cannot do this call from epl. I would suggest we introduce an additional parameter to the init-function of the mysql-backend that holds the encoding for the client's connection and its collation. If preset, we call "SET NAMES".

[0] http://dev.mysql.com/doc/refman/5.5/en/charset-connection.html

**Comment by JohnMcLear** [comment]
@webzwo0i what's your progress here?

**Comment by webzwo0i** [comment]
progress slowly :( my branch is at https://github.com/webzwo0i/etherpad-lite/tree/utf8-to-utf8mb4-migration but not worth to try out now.
I might have encountered a browser issue. chromium and ff destroy UTF-16 surrogate pairs on backspace. There where bugs in this area in the past, so not sure if it is a regression. Need to search for this in their bug trackers or even handle the backspace-key in epl (which I think should be avoided. But this would require a small fix in sendkeys).

**Comment by JohnMcLear** [comment]
Okay well of you can land a fix this weekend that would be great as were looking to push a release today and on late Sunday or early Monday :)
----- Reply message -----

**Comment by Pita** [comment]
Hey webswo0l, I have some free time this weekend and I'm happy to help. Let me know if there is anything I can do.

**Comment by webzwo0i** [comment]
mh maybe it's not a good idea to fix this now. We need to test all database backends too, to see if everything is okay with long pad names (somehow related to https://github.com/ether/etherpad-lite/issues/2583). Probably mysql is safe because in current versions it counts characters and not bytes but I get a limit on 25 4byte-utf8 chars. (I think it's just the regex that counts chars that is unaware of surrogates)
Could be the case other databases handle this in other ways...

So what I would propose for the moment is this: I do a pull request with my workarounds for the crashes which are caused by not filtering chars above U+FFFF. I include filtering for pad names, pad texts, chat messages, user names (anything else you can think of?).

I definitly want to support the full Unicode range in the future...

@Pita Could you take a look at https://github.com/Pita/ueberDB/pull/76 ?
Also, I found no way except patching ueberDB to make the cache-size customizable. This would aid debugging (because I sometimes I want to test against the cache and sometimes against the database directly) and maybe would even help high-load epl instances.
https://github.com/ether/etherpad-lite/issues/1936#issuecomment-80614328 was my attempt to test encodings, maybe you have a better idea? (on-the-fly cache-size changes or disabling the cache for certain queries imo both require tricky changes in ueberDB)

One last thing: I don't know a way to store the connection-encoding for clients directly in the database (except changing my.cnf and affecting every database). Thus, I need a way to do this in db initialization in exports.database.prototype.init
```db.query("set names utf8mb4 collate utf8mb4_bin",[],function(err)
    {
      if(err){
          throw err;
        }
    });
```
Would it be possible to expose some wrapper so I could do "set names" from epl? An alternative is to include a way to specify the connection-encoding and you do "set names" somewhere in mysql_db.js
Every suggestion would be great...
thxalot! :)

**Comment by RubenKelevra** [comment]
My Pad-Installation seems to have some serious bugs now, how do I fix this:


# mysql -u user -D database -h dbserver -p -e 'select `key` from `store` where `key` like "pad:%:revs:1";'|sed -e 's/:revs:[0-9]*$//g'|sed -e 's/^pad://g'|xargs -L1 node ./bin/checkPad.js
Enter password: 
[2015-09-13 13:00:00.994] [ERROR] console - Pad does not exist
[2015-09-13 13:01:14.509] [ERROR] console - Bad changeset at revision 334 - Cannot read property 'changeset' of null
[2015-09-13 13:01:14.635] [ERROR] console - Bad changeset at revision 464 - Cannot read property 'changeset' of null
[2015-09-13 13:02:45.444] [ERROR] console - Bad changeset at revision 3562 - Cannot read property 'changeset' of null
/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'meta' of null
    at /usr/share/webapps/etherpad-lite/bin/checkPad.js:103:64
    at done (/usr/share/webapps/etherpad-lite/src/node_modules/async/lib/async.js:135:19)
    at /usr/share/webapps/etherpad-lite/src/node_modules/async/lib/async.js:32:16
    at Object.callback (/usr/share/webapps/etherpad-lite/bin/checkPad.js:85:11)
    at /usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CloneAndAtomicLayer.js:100:17
    at /usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:185:7
    at Query._callback (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/mysql_db.js:115:5)
    at Query.Sequence.end (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
[2015-09-13 13:05:51.575] [ERROR] console - Pad does not exist
[2015-09-13 13:06:05.726] [ERROR] console - Pad does not exist
xargs: unmatched einfache quote; by default quotes are special to xargs unless you use the -0 option

**Comment by mikkorantalainen** [comment]
Any progress with UNICODE characters above U+FFFF? Newer mobile OS versions provide an easy input method for emotions and other characters above U+FFFF so this is getting pretty normal.

**Comment by JohnMcLear** [comment]
bump @webzwo0i

**Comment by mikkorantalainen** [comment]
It turns out that in addition to database utf8mb4 changes one really important change is in `settings.json`:
"dbSettings" : {
//...
"charset" : "utf8mb4",
}

Without that, ueberDB does not use `utf8mb4` for the database connection and characters above U+FFFF get mangled.

It's also worth noting that the `/etherpad/api/1.2/getHTML` REST API call returns content with `CESU-8` encoding instead of `UTF-8`. The difference is meaningful only for characters above U+FFFF.

**Comment by webzwo0i** [comment]
thanks for finding this!  this is a perfect replacement for the ugly "set names..." hack, did not know the mysql-lib provided this and ueberDB seems to pass the setting to it

**Comment by mikkorantalainen** [comment]
I didn't either. Fortunately ueberDB is an open source project so I just read enough source code to understand the "supported" features. Mysql-lib was documented well enough that the only thing required was to figure out which configuration parameter to modify.

**Comment by JohnMcLear** [comment]
Can we please submit a PR to ueberDB and/or Etherpad w/ the UTF8 fixes?

**Comment by Gared** [comment]
See #2862 @JohnMcLear @mikkorantalainen

**Comment by dcht00** [comment]
Hi, I'm recently having problems on both of my instances and they seem to be related to encoding.
Could somebody please give clarity to this - what's the current settings in full?

* What does a proper `show variables where Variable_name like 'character_set%' or Variable_name like 'collation%';` show for you?
* What's a proper my.cnf / way to get there (for a new DB / for existing DBs with "latin" or "utf8" collation/character sets)?
* Is it necessary for older installs to "migrate" / change encodings? Should the procedure above from @webzwo0i be followed, is it safe, or not? I used to run without `"charset" : "utf8mb4"  ` in settings.json, should I just add that, what else do I need to do / make sure? 

This would be good to have at
https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL

Thanks, I'm a bit confused.

**Comment by Gared** [comment]
@dcht00 "show variables" is just the info about your current connection settings and is not related to the way how etherpad connects to the database, except you want to manually change something on your command line.
It's necessary for all installations, because you can destroy pads with a single character. Yes, please follow the advise from @webzwo0i and migrate your table. After that, change the charset in the settings.json to ```utf8mb4```

**Comment by dcht00** [comment]
@Gared thanks for reply - you're right of course. But "character_set_database" and "collation_database" describe the DB's settings, and as I asked I'd like to see somebody answer my questions above, to have a sanity check. Like this:
```
mysql> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

mysql> show variables like 'collation%';
+----------------------+-------------------+
| Variable_name        | Value             |
+----------------------+-------------------+
| collation_connection | utf8_general_ci   |
| collation_database   | latin1_swedish_ci |
| collation_server     | latin1_swedish_ci |
+----------------------+-------------------+
3 rows in set (0.00 sec)

```

This really should make it to the wiki as well...

**Comment by JohnMcLear** [comment]
Closing this because I added lots of code recently to enforce utf8 et al.

**Comment by muxator** [comment]
@JohnMcLear, just to be clear: the code recently committed does not "enforce" anything. :)

We have a warning that checks if `settings.json` and the database charset are coherent, and ueberDB's documentation suggests fixes for utf8.

There may still be something to be merged, but today it is still not there. :)

**Comment by JohnMcLear** [comment]
+1
