### ISSUE TITLE
JSON-PROBLEM shuts server down

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#2522]
A few pads are invalid on my instance and every time these pads are called I get a JSON-PROBLEM-Exception:
```
[2015-02-18 20:13:48.167] [ERROR] console - JSON-PROBLEM (pad:49Xv36g3re93MSV):{"atext":{"text":"some text\n\n
[2015-02-18 20:13:48.173] [ERROR] console - gracefulShutdown...
[2015-02-18 20:13:48.173] [ERROR] console - Async Stacktrace:
    at /opt/eplite/etherpad-lite-dev/src/node/handler/PadMessageHandler.js:1306:5
    at /opt/eplite/etherpad-lite-dev/src/node/handler/PadMessageHandler.js:1042:16
    at /opt/eplite/etherpad-lite-dev/src/node/db/PadManager.js:171:10
    at Object.callback (/opt/eplite/etherpad-lite-dev/src/node/db/Pad.js:385:8)

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/CacheAndBufferLayer.js:164:24
    at Query._callback (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/mysql_db.js:116:5)
    at Query.Sequence.end (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/eplite/etherpad-lite-dev/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
```
After that the instance shutting down. I don't know how invalid JSON is getting into the DB, but shutting down the server cause of this problem is very bad.
Knowing which pads causing this error can lead to a DoS...

**Comment by JohnMcLear** [comment]
Dump the sql for these pads so we can debug?

I have seen this error before btw, I had to remove the pads to fix...  I have no idea how this data gets in as UeberDB explicitly only writes sanitized JSON!

**Comment by webzwo0i** [comment]
@Gared 
can you confirm you are running utf8?
mysql> show variables where Variable_name like 'character_set%' or Variable_name like 'collation%';

**Comment by Gared** [comment]
@webzwo0i Yes, the db is running on utf8:
collation_server is utf8_general_ci and also the table and the columns are set to utf8.

I will wait for this issue until utf8mb4 is approved to fix this problem.

**Comment by JohnMcLear** [comment]
We still think this is due to utf8 issues, we're working on a solution =) cc @webzwo0i

**Comment by elijh** [comment]
We have started to see this frequently. The only solution has been to delete the pad. It is hard to figure out which pad is the problem. It would help a lot if:

(1) JSON errors did not cause etherpad-lite process to die, bringing down the whole server in an endless death spiral of repeated restarts.
(2) JSON errors would log the pad id that caused the problem.

Then I could produce a corpus of several texts that cause the problem.

**Comment by elijh** [comment]
Oh, and we use mysql with a utf8 collation.

**Comment by elijh** [comment]
on second thought, it is going to be tricky to find what text is causing the problem, if indeed it is particular text. the problem is that the JSON error is triggered because the database record is truncated. for example:

```
{"atext":{"text":"blah blah
```

If I take that text ('blah blah' in this example) and paste it into a new pad then it works fine. This leads me to believe that if it is a character(s) that is causing the problem, then whatever that character is is no longer in the database.

and yes, the pads that i have seen this with do tend to have a variety of languages mixed together. the crash today was triggered by a pad with french, english, and arabic. maybe it is a RTL issue?

**Comment by webzwo0i** [comment]
trying to prevent crashes and compensate for databases that only support UTF8 with up to three bytes on https://github.com/ether/etherpad-lite/tree/issue-2522-broken-json

**Comment by elijh** [comment]
oh, that is a good thought!

to translate, i think what @webzwo0i is saying is that mysql only supports three byte utf8 and chokes very badly when it gets a sequence of characters with 4 byte utf8. The result was that mysql would truncate the string, which is exactly what we are seeing here.

Perhaps the easiest fix is to switch from the utf8 character set to the utf8mb4 character set. This is possible in mysql v5.5.3 and later.

https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by cboylan** [comment]
We just hit this ourselves. Would it also be possible to not kill the entire server when etherpad-lite runs into issues like this? Can it return an HTTP 500 error for the specific etherpad but otherwise let the rest of the server continue running? As is it got into a restart loop where JSON-PROBLEM occurs, etherpad-lite gracefully shuts down, init starts it up again only to run into the same JSON-PROBLEM.

**Comment by JohnMcLear** [comment]
@cboylan node runs in a single thread so when it hits an exception the stack bubbles up all the way to the top.

**Comment by elijh** [comment]
changing the charset to utf8mb4 seems to have done the trick.

**Comment by akosiaris** [comment]
Hitting the same bug as well. Stacktrace below. Would love to be able to find out the pad easily in order to delete it. 

```
[2015-06-22 18:44:09.758] [ERROR] console - JSON-PROBLEM:{"atext":{"text":"Anybody here come on at 7:15\n\n❤
[2015-06-22 18:44:09.762] [ERROR] console - Async Stacktrace:
    at /usr/share/etherpad-lite/src/node/handler/PadMessageHandler.js:1312:5
    at /usr/share/etherpad-lite/src/node/handler/PadMessageHandler.js:1047:16
    at /usr/share/etherpad-lite/src/node/db/PadManager.js:171:10
    at Object.callback (/usr/share/etherpad-lite/src/node/db/Pad.js:400:8)

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/share/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:164:24
    at Query._callback (/usr/share/etherpad-lite/src/node_modules/ueberDB/mysql_db.js:115:5)
    at Query.Sequence.end (/usr/share/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/usr/share/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/usr/share/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/usr/share/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/usr/share/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/usr/share/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/share/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
```

**Comment by akosiaris** [comment]
Got a dump of the pad as well
```
select `key`, value from store where `key`='pad:ips' into outfile '/tmp/ips.sql';
cat /tmp/ips.sql
pad:ips	{"atext":{"text":"Anybody here come on at 7:15\\n\\n❤
```

I am getting the distinct feeling that little heart is the problem. You might wanna raise priority on this. It's a possible DoS

**Comment by JohnMcLear** [comment]
@akosiaris check your database and table encoding.

**Comment by JohnMcLear** [comment]
also bump @webzwo0i

**Comment by akosiaris** [comment]
@JohnMcLear utf8_general_ci. Anything else you need from me to reproduce, please let me know

**Comment by JohnMcLear** [comment]
Best thing I'd suggest doing right now is console logging out that padId from the pad object and killing that pad.  @webzwo0i has a fix but I'm waiting on a PR with it in so I can merge it -_-

**Comment by JohnMcLear** [comment]
btw it should be ``utf8mb4_bin`` afaik no?

**Comment by akosiaris** [comment]
Already killed that pad. It took a while to find it. We host a pretty large etherpad installation. As far as `utf8mb4_bin` goes, it's a superset of utf8 with an extra byte to support all the UTF8 supplemental characters and planes. I suppose we should do it.

**Comment by elijh** [comment]
for us, switching to utf8mb4 did the trick. no problems since then. it did, however, require us to keep the service offline for a day (changing charsets on a large db is surprisingly slow).

i updated the wiki so that the instructions now use utf8mb4 https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL

**Comment by akosiaris** [comment]
@elijh OK, good to know. We 'll start the process ourselves as well. We will be doing it with the service online. Let's see how long that takes. I 'll report back here afterwards.

**Comment by Gared** [comment]
@elijh Thanks for your feedback. We also have to migrate to this charset. Can you provide information on your database hardware and etherpad table size so we can estimate how much time we will need to do it.

**Comment by JohnMcLear** [comment]
Also let's document the commands used here for science 'n stuff

**Comment by akosiaris** [comment]
@JohnMcLear I think they are already documented by @elijh at https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL , step 7.

That should help people fix their database installation so that they no longer get bit by this. That being said, not getting bit by this ever would be great. I suppose https://github.com/ether/etherpad-lite/commits/issue-2522-broken-json may be a fix ?

**Comment by JohnMcLear** [comment]
I did this migration on beta.etherpad.org too, I deleted all rows from table before doing it though so can't give any idea of computing time required.

**Comment by akosiaris** [comment]
@Gared, show table status said 55M rows. It's InnoDB so that's an approximation. I am not doing an select count(*), sorry. Hardware is a PowerEdge R510 with 64G of RAM. This is not a dedicated etherpad database, but rather hosted with other projects, but it is a rather idle box. Disks are 15K RPM 300GB drives. Total conversion time with 

```
ALTER TABLE etherpadlite.store 
CHANGE `key` `key` varchar(100) CHARSET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', 
CHANGE `value` `value` longtext CHARSET utf8mb4 COLLATE utf8mb4_bin NOT NULL, 
CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

was about 15 mins. Your milleage will probably vary.

**Comment by cboylan** [comment]
I am not sure this completely fixes the issue. After upgrading to MySQL 5.6 and performing the DB conversion as described in https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL I see console errors from the client running in chromium:

    Uncaught Error: Failed assertion: Invalid changeset (checkRep failed) VM747:5871
    error VM747:5871
    assert VM747:5885
    exports.checkRep VM747:6116
    setDocAText VM747:765
    makeChangesetTracker.withCallbacks.f.setDocumentAttributedText VM747:198
    (anonymous function) VM747:10197
    (anonymous function) VM747:194
    inCallStack VM747:471
    inCallStackIfNecessary VM747:540
    makeChangesetTracker.withCallbacks VM747:191
    self.setBaseAttributedText VM747:10183
    editorInfo.ace_setBaseAttributedText VM747:997
    (anonymous function) VM747:5476

This is running the latest commit on the develop branch (2bf16fe09fe9a6af804666d15ff4704620369d9f). It looks like the client is breaking on the encoding if the pad has 4 byte utf8 characters.

I do note that the service itself continues to run rather than restarting in a loop and pads without the 4 byte characters work fine. So this is an improvement but it doesn't fix all of the issues and can still DoS specific pads.

**Comment by elijh** [comment]
At the time, I think our etherpad-lite db was about ~ 60GB. There may have been something wrong, but it took over 12 hours for us. We followed the directions here https://mathiasbynens.be/notes/mysql-utf8mb4 (you need to potentially change the size of some of the fields since now more bytes are needed for the same length of strings). 

However, we disable collation entirely because we were not able to migrate to utf8mb4_bin. For some reason, the command to change the collation to utf8mb4_bin wanted to treat "cafe" and "café" as the same string, and it bombed out for unique fields saying that a duplicate value already existed. I don't know why collation would care, since I thought it just cares about order, but when we just dropped all the collation it worked fine. A quick skim through the code made me think that etherpad lite doesn't use any "ORDER BY" SQL anyway.

**Comment by JohnMcLear** [comment]
cc @webzwo0i

**Comment by Gared** [comment]
@cboylan Please check this pull request #2862

**Comment by simsasaile** [comment]
Also hitting this issue. Is there any way to rescue the pads data? It's quite important for me.

**Comment by webzwo0i** [comment]
Try export https://domain/p/your-padid/export/etherpad

**Comment by simsasaile** [comment]
Hi webzwo0i,

thank you for your advise, unfortunately this leads also to a shutdown of etherpad in my case. But it's ok, I used a two day old backup of my database to recover most information of my pad.

**Comment by danfowler** [comment]
Ran into this myself.  Have a backup, so I tried to use the `deletePad` API method, but it failed, too.

    [2016-09-07 21:18:30.395] [INFO] API - RESPONSE, deletePad, {"code":2,"message":"internal error","data":null}

**Comment by helioloureiro** [comment]
From times to times I'm hit by this problem as well.  It would be nice if etherpad could handle the error and display some message instead just crash.  It kills all other pads just because of one.

**Comment by almereyda** [comment]
In continuation of the errors caused by incomplete JSON, I would like to leave here some SQL commands that allowed us to repair our Etherpad instance into a state, in so the server wouldn't crash anymore.

Before we could operate on the UTF-8'ified database, we created a `latin1` export

    docker-compose exec mariadb sh -c 'mysqldump --verbose -u${MYSQL_USER} -p${MYSQL_PASSWORD} --databases ${MYSQL_DATABASE} --add-drop-database --opt --skip-set-charset --default-character-set=latin1 --skip-extended-insert' > latin1.sql

applied few transformations within the dump

```shell
perl -i -pe 's/40100 DEFAULT CHARACTER SET latin1/40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin/' latin1.sql
perl -i -pe 's/character_set_client = utf8 /character_set_client = utf8mb4 /' latin1.sql
perl -i -pe 's/varchar\(100\) CHARACTER SET utf8/varchar\(100\) COLLATE utf8mb4_bin/' latin1.sql
perl -i -pe 's/longtext COLLATE utf8_unicode_ci NOT NULL/longtext COLLATE utf8mb4_bin NOT NULL/' latin1.sql
perl -i -pe 's/InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci/InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin/' latin1.sql
```

and then converted the file of unknown depiction (`file -i latin1.sql` didn't show it as `latin1`)

    iconv -f ISO-8859-1 -t UTF-8//TRANSLIT latin1.sql -o utf8.sql

into the usable `utf8.sql`.

Since our database would by now start with explicit UTF-8 support enabled

```yaml
  mariadb:
    image: mariadb:10
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - "/data/bases/etherpad-mariadb-utf8mb4:/var/lib/mysql"
    networks: ["backend"]
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        compress: 'true'
```

we could now restore the dump

```shell
docker-compose exec -T mariadb sh -c 'mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} --default-character-set utf8mb4 ${MYSQL_DATABASE}' < utf8.sql
```

inspect it for errors

```sql
select `key` from store where `key` like 'pad:%' and value not like '%}';
```

and then adapt it according to our findings:

```sql
update store set value = CONCAT(value, '"}}') where `key` like 'pad:%' and `key` not like 'pad:%:revs:%' and `key` not like 'pad:%:chat:%' and value not like '%}';

update store set value = CONCAT(value, '"}') where `key` like 'pad:%:chat:%' and value not like '%}';

update store set value = CONCAT(value, '"}}}') where `key` like 'pad:%:revs:%' and value not like '%}' and value like '%changeset%meta%';

update store set value = CONCAT(value, '"}') where `key` like 'pad:%:revs:%' and value not like '%}' and value not like '%changeset%meta%';
```

This we would recreate from itself

```shell
docker-compose exec mariadb sh -c 'mysqlcheck -u root -p${MYSQL_ROOT_PASSWORD} --auto-repair --optimize --all-databases'
```

and have a new database running that doesn't crash the server anymore, but now only complains about corrupt pads:

```text
web_1      | [2022-10-26 18:55:52.745] [INFO] access - [CREATE] pad:some-pad-name socket:ZGOvIQv1XJ4tSH48AAAD IP:172.18.0.1 authorID:a.hhyRKf9t8jWNSQH2
web_1      | [2022-10-26 18:55:52.745] [ERROR] message - TypeError: Cannot read properties of undefined (reading 'indexOf')
web_1      |     at Object.exports.moveOpsToNewPool (/opt/etherpad-lite/src/static/js/Changeset.js:1641:22)
web_1      |     at Object.exports.prepareForWire (/opt/etherpad-lite/src/static/js/Changeset.js:1848:25)
web_1      |     at handleClientReady (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:913:40)
web_1      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
web_1      |     at async Object.exports.handleMessage (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:326:28)
web_1      |     at async /opt/etherpad-lite/src/node/handler/SocketIORouter.js:76:14
web_1      | [2022-10-26 18:55:52.746] [ERROR] socket.io - Error handling pad message from ZGOvIQv1XJ4tSH48AAAD: Error: CLIENT_READY: corrupt pad
web_1      |     at Object.exports.handleMessage (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:363:11)
web_1      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
web_1      |     at async /opt/etherpad-lite/src/node/handler/SocketIORouter.js:76:14
web_1      | [2022-10-26 18:55:52.816] [INFO] access - [LEAVE] pad:CI-Herbst-2022-Programm socket:ZGOvIQv1XJ4tSH48AAAD IP:172.18.0.1 authorID:a.hhyRKf9t8jWNSQH2
```

```shell
# docker-compose exec -T mariadb sh -c 'mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} --default-character-set utf8mb4 ${MYSQL_DATABASE}' <<EOF                                  
> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
> EOF
Variable_name   Value
character_set_client    utf8mb4
character_set_connection        utf8mb4
character_set_database  utf8mb4
character_set_filesystem        binary
character_set_results   utf8mb4
character_set_server    utf8mb4
character_set_system    utf8mb3
collation_connection    utf8mb4_bin
collation_database      utf8mb4_bin
collation_server        utf8mb4_bin
```

No more errors appear in the database:

```shell
# docker-compose exec -T mariadb sh -c 'mysql -u$MYSQL_USER -p"$MYSQL_PASSWORD" --default-character-set utf8mb4 ${MYSQL_DATABASE}' <<EOF
select \`key\` from store where \`key\` like 'pad:%' and value not like '%}';
EOF
Empty set (27.023 sec)
```
