### ISSUE TITLE
Replace AbiWord by a different import/export processor like LibreOffice (see also unoconv wrapper)

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#254]
As AbiWord is very difficult to install with its numerous dependencies, I suggest to replace AbiWord by alternative tools which are easier to install and better maintained.

I contacted the AbiWord developers, but unsuccessfully with the view to fix several multi-platform installation issues (for example, on LINUX SLES), and to fix the "AbiWord crashes on certain input files" problems. They also stated that AbiWord is not the best tool for (our EPLITE) import/export tasks.

**Comment by mrbabbs** [comment]
Hi everyone,
I know the issue is closed, but it could help someone.
I developed a basic import plugin "ep_document_import_hook" to import document with different tools than AbiWord. 
Currently, it only uses LibreOffice to import documents, but who wants can fork.
The plugin is also available in /admin/plugins.
