### ISSUE TITLE
Plugin Development: Accessing internal objects

### ISSUE THREAD

**Issue by tm-linkwerk** [ether/etherpad-lite#2554]
Hi, 
I'm trying to manipulate the document (e.g. set/remove attributes) when the user clicked a toolbar button. The first thing I need is the documentAttributeManager which is provided in the context-argument of some hooks, e.g. aceInitialized. 

So in the aceInitialized-function I register an onclick-Handler, which calls context.documentAttributeManager.removeAttributeOnLine. Unfortunately I get a javascript error telling me that "currentCallStack is null". 

Due to the lack of documentation I use firebug to try out how objects like documentAttributeManager behave. I don't know a way to access them outside a hook-function (is there one?). So I used aceInitialized to make them global. But I often run into the same error that the callstack is null. 

I don't know what currentCallStack is, but I began to edit ace2_inner.js and inserted some `if (currentCallStack) { ... }` around the two/three crucial code parts and after it, removing line attributes with documentAttributeManager worked. 

Now I don't really know what I did there (one code part had to do with handling undo/redo) and before going on and submitting a pull request I would like to ask if my approach is reasonable or if there are better ways to get around my problem accessing documentAttributeManager.

**Comment by JohnMcLear** [comment]
Have you taken a look at other plugins such as tasklist?

On 17 Mar 2015 17:31, tm-linkwerk <notifications@github.com> wrote:

Hi,
I'm trying to manipulate the document (e.g. set/remove attributes) when the user clicked a toolbar button. The first thing I need is the documentAttributeManager which is provided in the context-argument of some hooks, e.g. aceInitialized.

So in the aceInitialized-function I register an onclick-Handler, which calls context.documentAttributeManager.removeAttributeOnLine. Unfortunately I get a javascript error telling me that "currentCallStack is null".

Due to the lack of documentation I use firebug to try out how objects like documentAttributeManager behave. I don't know a way to access them outside a hook-function (is there one?). So I used aceInitialized to make them global. But I often run into the same error that the callstack is null.

I don't know what currentCallStack is, but I began to edit ace2_inner.js and inserted some if (currentCallStack) { ... } around the two/three crucial code parts and after it, removing line attributes with documentAttributeManager worked.

Now I don't really know what I did there (one code part had to do with handling undo/redo) and before going on and submitting a pull request I would like to ask if my approach is reasonable or if there are better ways to get around my problem accessing documentAttributeManager.

**Comment by JohnMcLear** [comment]
@tm-linkwerk can this be closed now?

**Comment by tm-linkwerk** [comment]
I think I found a way now, to make internal objects accessable in firebug:

1. hook into postAceInit and aceInitialized, they provide the objects { ace={...}, pad={...}}, and { editorInfo={...}, rep={...}, documentAttributeManager={...}} via context argument. 

2. store the needed internal objects somewhere to the global accessable context.

3. call `editorInfo.ace_inCallStackIfNecessary('xyz', function () { 
/*do something with one of those object*/ });`

I'm not sure what the first string argument (called type) of ace_inCallStackIfNecessary is exactly for (see https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L534), as I still dont fully understand how the callstack works and I don't know if this causes any unwanted side effects. 

One could wrap that behind an interface in the core, a debugging plugin or similar.
