### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#256]
Right to Left support for Arabic etc.

**Comment by ahangarha** [comment]
I think this issue needs to be opened again since it is not solved.

As a person whose native language is Persian (with RTL script) many times it happens that I write documets in which you may find both English and Persian. Lets talk about the example of writting something related to some python script. The body text is in Persian and therefore RTL while the python scripts are in English and therefore LTR. So applying a general direction to the document is not a solution.

I suggest the render engine from Markdown to HTML be modified and apply bidi methods to the HTML elements so if a paragraph starts with letter in RTL scripts, the whole paragraph become RTL and if it is in Latin, it goes LTR.

This is how many text editors work.

Should we continue this discussion here or should I open a new issue?

**Comment by peylight** [comment]
Fix it please.
