### ISSUE TITLE
peerDeps will be broken

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2659]
Installing ep_slideshow...

```
npm WARN peerDependencies The peer dependency ep_headings2@>=0.0.8 included from ep_slideshow will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by JohnMcLear** [comment]
Conversation here: https://github.com/npm/npm/issues/6565
TLDR; ?``

**Comment by JohnMcLear** [comment]
@othiym23 I read through the npm#6565 post and I'm still non-the-wizer as to how we should go about replacing our peerDependencies usage with something else?

Plugin(a) in Etherpad might depend on peerDependencies to install other plugins([b]) that plugiin(a) might depend on.  An example is here: https://github.com/JohnMcLear/ep_slideshow/blob/master/package.json

This functionality works perfect for our use case and we have not experienced any negative side effects.

Can you please TLDR; the problem and TLDR; a proposed solution?

**Comment by othiym23** [comment]
From https://github.com/npm/npm/blob/master/CHANGELOG.md#peerdependencies:
> This shifts the responsibility for fulfilling peer dependencies from library / framework / plugin maintainers to application authors, and is intended to get users out of the dependency hell caused by conflicting peerDependency constraints. npm's job is to keep you out of dependency hell, not put you in it.

So, in the case of `ep_slideshow`, it looks like it depends directly on `ep_headings2`, and the simplest way to handle the case where plugins are depending on other plugins is to express that as a simple `dependency`. I think in this case, it'll work fine. There are two more complicated aspects of this problem:

1. A plugin is written in such a way that it needs to be a singleton, either because of its own state or resources that it needs exclusive access to, or because of how EtherPad's plugin architecture works. The position of the npm team is that this is an architectural anti-pattern that depends on an implicit behavior of Node's module loader. Code written this way should probably be rewritten to use globals explicitly, or to use a dependency injection strategy that doesn't depend on the module being at any particular position in the tree.
2. A plugin may end up in the tree multiple times. If the dependency is being installed by `npm@3`, then this should happen relatively infrequently, and in the cases in which it does, it's almost inarguably the right thing to happen, because this is exactly the situation that would have led to a `peerDependency` conflict in older versions of npm (due to conflicting semver ranges). Most of the time, the hoisting of dependencies in `npm@3` will mean that plugins declared as `dependencies` will end up as peers.

So, the simple solution is for plugins depending on other plugins is to move the dependencies from `peerDependencies` to `dependencies`. In which cases will this not work for EtherPad?
