### ISSUE TITLE
User-configurable font size

### ISSUE THREAD

**Issue by NathanNeff** [ether/etherpad-lite#2671]
This is a request for ability to show a font-size drop down or some other way to
configure the font size for individual pages.  This was a feature
on older versions of Etherpad, and has apparently been removed.

https://www.evernote.com/l/AOLCwdPSNWxEqYEX3oBnIolDcgJRf-4wMTA

The font-size drop down would be page-specific, and user-configurable.
This would allow end-users to increase / decrease the font size shown
for a particular page, without needing to edit a CSS page or javascript code.

What was the reason for removing this drop-down?

**Comment by JohnMcLear** [comment]
This would be very easy to do, few hours dev time tops probably.

It should be done as a plugin.

It was removed because a browser should be used to manage font sizes.

**Comment by NathanNeff** [comment]
The problem with relying on a browser to manage font sizes
is that when I increase the fonts using using Cmd + "+" button in my browser,
*all* the fonts on the page (including menus, buttons, etc) are increased.

In many cases, buttons, menus, etc are pushed off the page -- see this screenshot:
https://www.evernote.com/l/AOKImWCeSdZPF4rG-i3ovO4UgJyIuHkBieU

Am I missing a simple way to use my browser to increase the font size for the Etherpad
text?

Thanks,
--Nate

**Comment by JohnMcLear** [comment]
Fair point.  I could make a plugin in an hour or so if you can create a bounty or pay me directly.

On 22 May 2015 17:18, Nathan Neff <notifications@github.com> wrote:

The problem with relying on a browser to manage font sizes
is that when I increase the fonts using using Cmd + "+" button in my browser,
all the fonts on the page (including menus, buttons, etc) are increased.

In many cases, buttons, menus, etc are pushed off the page -- see this screenshot:
https://www.evernote.com/l/AOKImWCeSdZPF4rG-i3ovO4UgJyIuHkBieU

Am I missing a simple way to use my browser to increase the font size for the Etherpad
text?

Thanks,
--Nate

**Comment by markusk** [comment]
Hm, isn't this resolved by this plugin?
https://npmjs.org/package/ep_user_font_size

**Comment by JohnMcLear** [comment]
"configure the font size for individual pages" - not "configure the font size for individual portions of text", so no, it isn't.

**Comment by markusk** [comment]
Sorry, my fault.

**Comment by NathanNeff** [comment]
This plugin looks like exactly what I want on primary pad.com

I don't want to configure font sizes for individual portions
of text.  I would simply like a drop-down-box at the top of the page, would
have something like 100% 125% 150%, etc.  When a user selects a size, the
font of the Etherpad text on the page is increased by a certain margin.

This feature was on older versions of Etherpad, and is now missing.

**Comment by Mte90** [comment]
With the high resolutions monitor it is very difficult to see properly text with a resolution 1920x1080 and his option today will be very useful

**Comment by joassouza** [comment]
@Mte90 I can work on it

**Comment by slel** [comment]
It is a common user interface problem to separate the magnification of
a whole webpage vs just a text portion of it.

Note that this very problem is solved in the [CoCalc](https://cocalc.com)
"Collaborative Calculation in the cloud" platform, where the CoCalc menu bar
inside the browser window has icons "small A" and "large A" that let the user
decrease or increase the font size for the text part of the interface, without
affecting the menu parts.

I wish a similar solution was implemented in Etherpad-Lite.

In [Software Carpentry](https://software-carpentry.org/) workshops, the
instructors, helpers and attendees use an etherpad to keep track of issues,
comments, links, discussions that arise during the workshop. In the
[January 2018, ENES Morelia](https://thanyta.github.io/2018-01-22-morelia/)
Software Carpentry workshop, I was acting as a helper, maintaining the
etherpad and displaying a portion of it to a large screen on the wall at
the front of the room, and had to increase size a lot for it to be readable.
Because of doing that with `cmd`-`+` or `ctrl`-`+`, most of the screen ended
up being eaten by the etherpad top and side parts (menu, chat, author names).

Finally, note that this issue has some relation to other etherpad-lite issues:

- kentonv/etherpad-lite#24: Can the font size be a little bigger?
  [https://github.com/kentonv/etherpad-lite/issues/24](https://github.com/kentonv/etherpad-lite/issues/24)

- etherpad-lite/#3233: Improved readibility in default font size and highlight colors
  https://github.com/ether/etherpad-lite/issues/3233

- etherpad-lite/#2671: User-configurable font size
  https://github.com/ether/etherpad-lite/issues/2671

**Comment by slel** [comment]
On CoCalc the icons are now
- a magnifying glass with a minus sign to decrease font sise
- a magnfiying glass with a plus sign to increase font size
I use it for remote teaching, it's very convenient to be able
to make everything tiny so that the menus and buttons take
very little space, but then increase the font size so that the
parts students care about are very readable.

**Comment by JohnMcLear** [comment]
@slel is that running latest develop?  What plugin?  IUs this with ep_font_size

**Comment by JohnMcLear** [comment]
@slel I checked using ep_font_size against develop and it looks fine.  I see people still want the ability to change ``zoom`` in The settings drop down?

**Comment by JohnMcLear** [comment]
I added more sizes to ep_font_size

**Comment by JohnMcLear** [comment]
I also realized you guys might be running older versions..  Since 1.8.3 (develop) the UI scales a LOT better.  

![image](https://user-images.githubusercontent.com/220864/79987416-4a586a00-84a5-11ea-9df5-d87dfa7c63e3.png)

**Comment by JohnMcLear** [comment]
@seballot I think the request here might be that the buttons hit a specific size (based on browser zoom) then don't take any more space?

I guess to avoid this extreme

![image](https://user-images.githubusercontent.com/220864/79987547-78d64500-84a5-11ea-97cf-007fe73021b3.png)

**Comment by seballot** [comment]
mmm, I think if people want to increase the size (by zooming the page), they want to increase all sizes. If they cannot read a line with standard font-size then they cannot read the icon of the button (which is main size)

And if they want to do such extreme, let's leave them :)

**Comment by JohnMcLear** [comment]
Closing because it works fine within realistic constraints.
