### ISSUE TITLE
Put the ability to chat etc. in Read Only under a setting flag

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2672]
Ie `readOnlyCanCommentAndChat`

**Comment by rugk** [comment]
Currently the behaviour is strange: In all "usual" situations the chat window is hidden (and not showable in the UI) when accessing the read-only mode.

However if you previously pinned the chat window (in read-write mode), so that it is always visible it is also visible in ro mode. But when you close (aka "minimize") it there it gets completely hidden (again).
