### ISSUE TITLE
Do not save new pad to database on initial GET request

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#2740]
We should save a pad to the database after the first change on the pad text.
There are some users that create a pad to see what etherpad is, but never do any changes on these documents or crawlers that request urls that opens new pads.
What do you think about this idea? Maybe I have time to implement this.

**Comment by bhldev** [comment]
Completed in #2923 

**Only saves initial key as read only, ex. saves the following**
{"key":"pad2readonly:DbNoSave4","val":"r.bbea3ea68384826a1456f6edc2ab9ed7"}
{"key":"readonly2pad:r.bbea3ea68384826a1456f6edc2ab9ed7","val":"DbNoSave4"}

**Does not save the following until first revision**
{"key":"pad:DbNoSave4:revs:1","val":{"changeset":"Z:bj>1|7=bi*0|1+1$\n","meta":{"author":"a.B7o63QPh4YbRdTs8","timestamp":1457914152598}}}
{"key":"pad:DbNoSave4","val":{"atext":{"text":"Welcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nGet involved with Etherpad at http://etherpad.org\n\nWarning: DirtyDB is used. This is fine for testing but not recommended for production. -- To suppress these warning messages change suppressErrorsInPadText to true in your settings.json\n\n\n","attribs":"|7+bi*0|1+1|1+1"},"pool":{"numToAttrib":{"0":["author","a.B7o63QPh4YbRdTs8"]},"nextNum":1},"head":1,"chatHead":-1,"publicStatus":false,"passwordHash":null,"savedRevisions":[]}}
