### ISSUE TITLE
Unaccessable pad after etherpad.com maintaince today recently

### ISSUE THREAD

**Issue by Akuukis** [ether/etherpad-lite#2779]
Hello,

[This](https://etherpad.net/p/EBUdzivoklis2) and [this](https://etherpad.net/p/EBUdzivoklis2-clean) pad  and  become unaccessible after maintaince today. I was working on them when connection was lost. Did clear cache, restart browser, tried other hardware&browser but no success. [Other](https://etherpad.net/p/EBUdzivoklis) pad  is ok, but was not edited at the or shortly before connection was lost to etherpad.com due maintaince. No errors seen in console.

Pressing F5 flashes text:
````
An error occured
The error was reported with the following id: '3j1PC0kxjOuwPYWIJJ1V'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: 3j1PC0kxjOuwPYWIJJ1V
URL: https://etherpad.net/p/EBUdzivoklis2
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1
TypeError: pad.collabClient is null in https://etherpad.net/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 266'
````

Is the content recoverable?

**Comment by 0ip** [comment]
Please do not post issues here that are not directly related to the Etherpad software.
For problems like these, please use the contact information given on the page in order to talk to the corresponding maintainer.

I was able to access your pads without any problems. As I said, for future questions, please take a look at https://etherpad.net/ or read the introductory text on a new pad.
