### ISSUE TITLE
BUG for API etherpad and speech recognition google

### ISSUE THREAD

**Issue by maximerinna** [ether/etherpad-lite#2816]
Hi , 
I am deaf and I use to communicate EtherPad, thank you for your work that allows us to talk about this a handy chat.

I meet a BUG and I wish to know if you verify or prove a solution.
I am not a developer, I do not know how to fix the code ....

Description of the problem :
The problem relates to the API, and to reproduce the error prove you do this:
1)	On a server you made a quick loop between 0.1 and 0.5 seconds in 1000 or 2000 shipment, each writing by sending text setText API function with the key pad on a remote network far side (the other side of the world ;-)

Example the word sending   padID canal3  
 
2) Well pad on the remote to go you have a following error screen: padID = canal3
 
 The words send in API from an html page javascript her visible but the error is present.
 Here is the code used to send the words padID = canal3
The variable that contains the messages that named: interim_span
This is a simple HTML variable:

 <div id="results"  >          
<span class="final" id="final_span"></span> <span class="interim"           id="interim_span"></span>  </div>

function envoipad() {         
 var d = document.getElementById("interim_span").innerHTML;          var messagecurseur = 'http://5.156.67.192:19001/api/1.2.10/setText?apikey=c765fdba320422c9adbb0861aa7ac2b110d20eb103d0a6a03d5dbe087521a919&padID=canal3&text=' + document.getElementById("final_span").innerHTML  ; 
    // window.open(messagecurseur , '_top', 'essai');  	MaFenetre = window.open( messagecurseur ,'essai','width=200,height=200' );                MaFenetre.opener.focus(); 	focus();              close(); }

Can you take a little time to do a check by replicating the problem?

if you please. This will make us a huge service.
I try the next module, but it does not work? 

https://www.npmjs.com/package/ep_speechinput
Actually what I want to do is send Google voice recognition in a speech to EtherPad that deaf can benefit from speech recognition.

But I can not do it ...

Example de speech recognition 
https://chrome.google.com/webstore/detail/voice-recognition/ikjmfindklfaonkodbnidahohdfbdhkn
and send in the one pad :     reading the text for the deaf
Bests 

Regards
![requeste_v01](https://cloud.githubusercontent.com/assets/7781584/10714922/df541e20-7b03-11e5-9052-0a67a1b8b366.png)

   RINNA maxime

**Comment by webzwo0i** [comment]
hi, thank you for this bug report. Be sure though that you don't unintentionally publish the API key of your installation (even if every pad is public you could delete the whole pad via the API...). If this was not intended you should change the API key.

Regarding speech input: This is probably a plugin issue and you would need to contact the original plugin author. Currently there is no "compatibility" check for plugins. You can easily install them but they can do anything to your instance.
Regarding the other issue: The client that is connected to the pad receives a changeset that could not be applied to the pad text because the number of chars in the text before applying the changeset is not the same as the reference value inside the changeset). Because you said this only happens via a high-latency network connection and when sending pad updates very fast I suspect a edge case bug in the way we apply changesets. Let's say the connected browser is at revision 23 and the server is at revision 50. The remaining 27 revisions are somewhere between the server and the browser for the browser to be received. If the browser receives a changeset (let's say 30) before it received all changesets 23-29 than there is a chance it cannot apply revision 30.

If you get this bug again could you do me a favour and check if a) reloading the pad(ctrl+shift+R) shows the current pad text (without error) and b) if you go to the timeslider, drag the slider to the first revision and press the play button no error is shown in the browser. I think this would back up the theory that it's related to receiving revisions out-of-order.

**Comment by maximerinna** [comment]
Hi, 
Thank you for your quick response, here is some information:

I try to slow down the sending speed is a line every 3 seconds, but the blockage happens

1) ctrl + shift + R makes it possible to clear the error, but the pad is no longer operational, no changes possible, as if it was freezing. 

2) The term "Chargement " is visible and does not go after a ctrl + shift + R
function envoipad() {     var d = document.getElementById("interim_span").innerHTML;     var messagecurseur = 'http://4.186.64.111:19007/api/1.2.10/setText?apikey=475845a320422c9ahgdshjgsjhdgac2b110d20ebfrlkjksjdkjsdfjh919&padID=canal3&text=' + document.getElementById("final_span").innerHTML  ;     // window.open(messagecurseur , '_top', 'essai');  	  sleep(3000);  	MaFenetre = window.open( messagecurseur ,'essai','width=200,height=200' );     MaFenetre.opener.focus(); 	focus();     close(); }

3) The return of the statue sending setText function is 0 

4)  The function doRepApplyChangeset length mismatch il line 492
UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

Uncaught Error: doRepApplyChangeset length mismatch: 189/55 in http://77.656.52.452:19001/p/canal4 at line 492'        
![requeste_v02](https://cloud.githubusercontent.com/assets/7781584/10717247/c975d60e-7b51-11e5-8617-95f15d7aef19.png)

**Comment by JohnMcLear** [comment]
Assuming I'm the author of this plugin can someone TLDR the actual issue here?

**Comment by JohnMcLear** [comment]
http://etherpad.org/doc/v1.6.0/#index_appendtext_padid_text should fix this...
