### ISSUE TITLE
Please show the version in the web interface

### ISSUE THREAD

**Issue by yurivict** [ether/etherpad-lite#2968]
Currently it is hard to tell from the web interface what version is running.

**Comment by Gared** [comment]
The etherpad server responses with the HTTP-Header "Server" and the version "Etherpad 32d9041 (http://etherpad.org)". 
Where would you expect the information about the version in the web interface?

**Comment by yurivict** [comment]
It can be to the left of "Import/Export" button, or on the "Pad Settings" box.

**Comment by Wikinaut** [comment]
I think, this can be closed, as the (github) version is shown in the **settings**, my pad shows
```
About
Powered by Etherpad-lite on node.js (git revision 5a0afa).
```
 
@yurivict pls. can you confirm my observation?

**Comment by Wikinaut** [comment]
@JohnMcLear I think this can be closed.

**Comment by Perflyst** [comment]
I can't see the version in the settings of a pad.

**Comment by lpagliari** [comment]
@Wikinaut I don't see that on pad settings either: https://beta.etherpad.org/p/LFP

![image](https://user-images.githubusercontent.com/836386/42591555-67ad117a-851d-11e8-982e-1886c0eb3f61.png)

Where do you see yours?

**Comment by muxator** [comment]
I am ok with showing the version in the web interface, since we are already putting it in a HTTP header.

However, I feel this should be under a configuration setting (both for the header and the web interface): preventing information disclosure about one's system does not save against a determined attacker, but at least slows down the laziest.

Since this is not directly related to this issue, I have opened a new one in #3423.

**Comment by Wikinaut** [comment]
@lpagliari  I have seen the version info in the settings in one of the pads I am using - cannot find that back.

**Comment by Perflyst** [comment]
I just upgraded to v1.7.5 and there is now only "Server: Etherpad (http://etherpad.org)" without commit hash or tag. What changed?

**Comment by muxator** [comment]
Thanks @Tristramg for implementing this (and #3423) with #3596.
