### ISSUE TITLE
Strange cookies are set and bypass cookie_path redirection 

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2985]
Two cookies are set:
- `test` (content: `test`) - I know this is probably an plugin... :expressionless:
- `token`

At least of the first one I want to get rid of.

Although I have set this in my nginx config, these two cookies do seem to byass this and set their path to `/`:

``` nginx
proxy_cookie_path / /etherpad/;
```

All other cookies (`prefs`, `language`, `express_sid`) are fine.

**Comment by JohnMcLear** [comment]
Try disabling plugins ........

**Comment by rugk** [comment]
Okay, now I disabled all plugins and I can see that this is *not* an issue with a plugin.

I could also identify the requests where this is set. You can see them in this gif:
![cookieetherpad](https://cloud.githubusercontent.com/assets/11966684/15714727/fb8d8368-281b-11e6-8f90-fb5ad8ff958b.gif)

So to summarize:
* the `test`cookie is first transmitted by the *second* socket.io request after the request to locales.json.
* the `token`request is first transmitted by the POST request to socket.io

I could reproduce it with the latest dev version (a7405825a8fa011bdea2a50fd6b0f2756abd674d).

Another thing I noticed:
When the connection breaks (because I e.g. restart Etherpad-lite) and Etherpad tries to connect to the Etherpad server again, the `token` cookie is restored:
![cookkierestore](https://cloud.githubusercontent.com/assets/11966684/15715409/a77d8af4-281e-11e6-8333-780ca716e08a.gif)


Reproduce:
1. Load an Etherpad
2. Delete the cookies `test` and `token`
3. Cause Etherpad to close the current websocket connection and having to reconnect (e.g. by restarting the Etherpad server)
4. When the reconnection succeeds the  `token` is set again

----

I also found the places in the source code where this cookies are presumably set:
* test: https://github.com/ether/etherpad-lite/blob/a3188cf3574234f17f927499c2f739c2bd5fd9d3/src/static/js/pad.js#L505
* token: https://github.com/ether/etherpad-lite/blob/a3188cf3574234f17f927499c2f739c2bd5fd9d3/src/static/js/pad.js#L194

----

So to come back to this issue about these cookies, here is what I think should be changed:
1. I don't like test cookies. Can Etherpad life without setting this cookie? Please remove it.
2. The `token` cookie circumvents [`proxy_cookie_path`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path) of nginx. Can you please fix this?

And BTW: Please reopen this issue.

**Comment by JohnMcLear** [comment]
Did you hit the instance directly or through a reverse proxy?

On 1 Jun 2016 11:35 p.m., rugk <notifications@github.com> wrote:

Okay, now I disabled all plugins and I can see that this is not an issue with a plugin.

I could also identify the requests where this is set. You can see them in this gif:
[cookieetherpad]<https://cloud.githubusercontent.com/assets/11966684/15714727/fb8d8368-281b-11e6-8f90-fb5ad8ff958b.gif>

So to summarize:

  *   the testcookie is first transmitted by the second socket.io request after the request to locales.json.
  *   the tokenrequest is first transmitted by the POST request to socket.io

I could reproduce it with the latest dev version (a740582<https://github.com/ether/etherpad-lite/commit/a7405825a8fa011bdea2a50fd6b0f2756abd674d>).

Another thing I noticed:
When the connection breaks (because I e.g. restart Etherpad-lite) and Etherpad tries to connect to the Etherpad server again, the token cookie is restored:
[cookkierestore]<https://cloud.githubusercontent.com/assets/11966684/15715409/a77d8af4-281e-11e6-8333-780ca716e08a.gif>

Reproduce:
1. Load an Etherpad
2. Delete the cookies test and token
3. Cause Etherpad to close the current websocket connection and having to reconnect (e.g. by restarting the Etherpad server)
4. When the reconnection succeeds the token is set again

________________________________

I also found the places in the source code where this cookies are presumably set:

  *   test: https://github.com/ether/etherpad-lite/blob/a3188cf3574234f17f927499c2f739c2bd5fd9d3/src/static/js/pad.js#L505
  *   token: https://github.com/ether/etherpad-lite/blob/a3188cf3574234f17f927499c2f739c2bd5fd9d3/src/static/js/pad.js#L194

________________________________

So to come back to this issue about these cookies, here is what I think should be changed:
1. I don't like test cookies. Can Etherpad life without setting this cookie? Please remove it.
2. The token cookie circumvents proxy_cookie_path<http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path> of nginx. Can you please fix this?

And BTW: Please reopen this issue.

**Comment by rugk** [comment]
Reverse proxy. Otherwise I could of course not use `proxy_cookie_path`.

**Comment by rugk** [comment]
Please reopen this issue.

**Comment by rugk** [comment]
Another thing BTW: In the local storage this value is saved:

```
debug = undefined
```

You jsu7t need to create a new pad to notice this.

**Comment by Gared** [comment]
@rugk The debug key is set by socket.io. It looks like we can't affect this behaviour

**Comment by rugk** [comment]
Okay, [I've created an issue](https://github.com/socketio/socket.io/issues/2610).

**Comment by rugk** [comment]
So actually it is a module called "debug". Do you really need that module? What about removing it?

**Comment by Gared** [comment]
We don't reference the module "debug". It's a dependency of socket.io

**Comment by rugk** [comment]
Okay, back to socket.io: https://github.com/socketio/socket.io/issues/2610#issuecomment-236422331

Why is a module called "debug" used in production versions?

**Comment by rugk** [comment]
So back to you, see this reply:
> Please see https://socket.io/docs/logging-and-debugging/.
>
>If you're using webpack, you could use something like strip-loader to remove those lines from your bundle (see example)

https://github.com/socketio/socket.io/issues/2610#issuecomment-302854781

**Comment by JohnMcLear** [comment]
No longer appear to be getting created.
