### ISSUE TITLE
unable to call API from jquery lite plugin / how to use my own app+editor ?

### ISSUE THREAD

**Issue by on-meetsys** [ether/etherpad-lite#3052]
Hello,

I am trying to add etherpad to my own web application, using a froala (https://www.froala.com/) editor. By now, I have etherpad working on server, and an iframe is well created on client, thanks to https://github.com/ether/etherpad-lite-jquery-plugin : 
`$('#idedit').pad({'host':'http://myhost.com:9001','padId':'mytest'})`

Fine. But now I can not find out how to access the API (https://github.com/ether/etherpad-lite/wiki/HTTP-API), for example to set the html content. If I call the HTTP API with padId='mytest', I have an error telling padId must be a string for example... Does the jquery lite plugin allows API calls ?

Then, I wonder what will be the solution to use froala editor... Is there a solution to make a div subscribe to etherpad services, with callbacks, without using iframe ? Or do I have to build this feature on the server side (and then how to get/set content + css on client ?) ?

I've taken time to find examples or to read the documentation, without success for now. 

Thanks.

**Comment by lpagliari** [comment]
Take a look on the backend tests. There's a call to the api to set html content of a pad here: https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/pad.js#L515. Print the url sent to `api.get()` and it might give you a hint on what is wrong with your call to the api.

**Comment by DanielBickley** [comment]
The jquery plugin merely assists in piping your Etherpad-lite installation at port 9001 into a web page via an iFrame. So, if you aren't proxying Etherpad-lite into your web app, then you're left to pull it in via iFrame, and using the jquery plugin is handy because it helps you set up all the parameters via the iFrame's URL query string.

In terms of the API, that is server-side directives, having nothing to do with the manner in which you embed Etherpad-lite into your web page (jquery plugin or proxy) - **as far as I know**. For example, I use the plugin to pull in my Etherpad-lite installation from port 9001 into my web app, and then I use server-side API calls using Php. That way, I can setHTML using a server-side API call during page creation, and then when the pad loads up in my iFrame, it will have done so with the content I plugged in just prior to page load using the setHTML call. I take this further by then using AJAX to run more server-side API calls behind the scenes. As @lpagliari pointed out, compare your API URL to what the specs require, and it should give you a hint. Make sure you are plugging your API KEY into your API call - that's crucial.

I'm not certain how well trying to run Etherpad-lite out of Froala will be. I mean, would you set/getHTML via API on every keypress in the Froala instance? Also, the tools offered in Froala vs Etherpad-lite are not synonymous. You may try simply using Froala throughout your web app, and then for real-time collaboration, pipe in an Etherpad-lite iFrame with a customized toolbar - that mimics your Froala styles. I've done something similar with TinyMCE.
