### ISSUE TITLE
Share different lines of content with different users

### ISSUE THREAD

**Issue by Tusharsb** [ether/etherpad-lite#3104]
Currently Etherpad would share the entire list of lines with all users. Envision is (for a plugin?) that would let pad author choose which lines of the text is to be shared with which particular user. Combined with Table-of-Contents plugin - the admin user can specify which headline (and its children lines) are to be shared with which particular user

This could enable a long document to be shared with collaborators. While all are contributing to the document, they might not be seeing the entire document but only the portion shared with them

To regulate which line is to be sent to which particular client - I think it has something to do with `src/node/db/Pad.js init()`.

I am new to etherpad lite. Can someone please guide me on how to go about implementing this feature ?

**Comment by lpagliari** [comment]
I'm not sure this is a plugin we can create right now, but if you want to try, here are some suggestions:

* To specify which user can see what: add a line attribute "allowing" an user to access the line. [ep_headings2](https://github.com/ether/ep_headings2) uses line attribs to set line style, so you can take a look on that plugin to check how you can implement this part;
* To hide lines user cannot access: this is the hard part. I could not think on a way to safely implement it, the only way that occurs me is to use CSS to hide it, which still allows user to see the line if he/she inspects the code and removes the CSS. But if this is not an issue for you, you can use some hooks like http://etherpad.org/doc/v1.6.0/#index_acedomlineprocesslineattributes, http://etherpad.org/doc/v1.6.0/#index_acepostwritedomlinehtml and http://etherpad.org/doc/v1.6.0/#index_aceattribstoclasses. To help you. Again, take a look on ep_headings2, it uses the same hooks;
* When an user edits something close to a line he/she cannot access, it might lose its line attribs (this happens due to the way Etherpad checks for changes on DOM), so make sure you implement http://etherpad.org/doc/v1.6.0/#index_collectcontentpre to read the line attribs from the line. ep_headings2 also uses this hook.
