### ISSUE TITLE
Embedding Hyperlinks in Pad

### ISSUE THREAD

**Issue by parceldesign** [ether/etherpad-lite#3178]
I'm not seeing any documentation or plugin support for embedding links into a pad, [like this](http://etherpad.org/). This would be a very helpful feature to have in a collaborative document editor! Am I overlooking something, or does Etherpad not support embedding links?

**Comment by lpagliari** [comment]
**As far as I know**, Etherpad only transforms URLs into links, but there's no way to change the text of the hyperlink.

Would be a very useful feature, I agree. Do you think you could implement it, @parceldesign?

**Comment by parceldesign** [comment]
@lpagliari I could probably implement this feature. Let me take a look at some similar plugins and see the level of complexity. This could be my first contribution to an open source project :)

**Comment by lpagliari** [comment]
This plugin might be useful for you: https://github.com/JohnMcLear/ep_font_color. You basically need to "mark" some text with an attribute (the URL), and make sure you build the HTML in accordance to that.

**Comment by parceldesign** [comment]
We're thinking alike—I'm looking at that plugin right now.

**Comment by lpagliari** [comment]
`ep_font_color` uses `color` as the attribute name, and the color name as value; you would use something like `hyperlink` as the attribute name, and the URL as the value.

**Comment by lpagliari** [comment]
Sweet! 👍

**Comment by parceldesign** [comment]
Shouldn't it be wrapped in a link tag, though? Giving a span element a hyperlink attribute wouldn't make the link work. Or is that assumption incorrect?

**Comment by lpagliari** [comment]
yes, you are correct. So [here](https://github.com/JohnMcLear/ep_font_color/blob/master/static/js/index.js#L55-L58), where you have:

```
    var modifier = {
      extraOpenTags: '',
      extraCloseTags: '',
      cls: cls
    };
```

you would need to change to

```
    var modifier = {
      extraOpenTags: '<a href="' + url + '">,
      extraCloseTags: '</a>',
      cls: ''
    };
```

**Comment by inicio** [comment]
Me again. Here's what I've got. [ep_embedded_hyperlinks](https://www.npmjs.com/package/ep_embedded_hyperlinks)

The only instance of Etherpad I have running is on Heroku, so I haven't a way to test it yet. If you can add it to the plugin list I'll try it out.

**Comment by inicio** [comment]
Ok, I've got a way to test it now. It's not working yet. The button is not registering in the editbar. You can resolve this thread, if you'd like. I'll continue working away on the plugin.

**Comment by lpagliari** [comment]
Awesome, @inicio!! \o/

**Comment by inicio** [comment]
Just wondering if I could open this issue up again for support. I have developed the basic logic to handle adding embedded hyperlinks, however I'm lost at how to integrate it with Etherpad's plugin hooks. 

Perhaps someone can take a quick read over my code [here](https://github.com/inicio/ep_embedded_hyperlinks) and see if I'm on the right track.

**Comment by lpagliari** [comment]
Sure thing! I took a look on `ep_embedded_hyperlinks` and it looks you are on the right track.

Some things I've noticed, might be useful for your next steps:

- on `aceCreateDomLine `:
  - your regex might not match all URLs (ex: "https://github.com/inicio/ep_embedded_hyperlinks/blob/master/static/js/index.js"). You can use this website for testing, it has some resources that might help you: https://regex101.com/. My suggestion would be to capture everything that is not a whitespace (`(?:^| )url:(\S*)`);
  - your parenthesis on the regex already capture the URL for you: instead of using `url.substr(4,url.length)`, you can simply use `url[1]` to get the full URL on the attribute value;
- explaining what the code on `aceInitialized` does: when the user embeds the link, you need to save the attribute on that part of the text. To do that, you need to have access to some values that are not available on the regular `$.onClick()` call, but that are available when Etherpad initialises all its components. So you bind your `doInsertLink` function to `context`, to have access to `context` later, when user clicks the "Embed" button. If you didn't do that, you would not be able to access `rep` or `documentAttributeManager` inside of `doInsertLink()`;
- I didn't get what is being done on `aceEditEvent`...
- right now, when I edit a line with an embedded link, the link is gone. That's what `collectContentPre` helps you to handle: every time a line is edited, this function is called for every node on that line. So you need to check if the node has an embedded link inserted by your plugin (disregard regular links typed on the text), and if so, make sure the node is marked with the correct attribute -- I believe that's what `context.cc.doAttrib(context.state,"url::" + url);` is trying to do.

Hope this helps on the next steps :-)

**Comment by inicio** [comment]
Thanks, Luiza. With your help I tracked down the error to somewhere between aceCreateDomLine and collectContentPre. Turns out I had forgotten to pass along the cls variable to my modifier. 

https://github.com/inicio/ep_embedded_hyperlinks/blob/master/static/js/index.js#L45

All good now! Glad to have contributed to this awesome project.

**Comment by lpagliari** [comment]
should I close the issue, then, @inicio ? You can keep posting here, if you have any question...

**Comment by inicio** [comment]
You can close it, @lpagliari.

**Comment by jekuno** [comment]
@inicio Short question: You wrote that you run etherpad on Heroku. How did you deploy it? I only know of https://github.com/bright-star/etherpad-lite-heroku which is quite outdated.

**Comment by inicio** [comment]
@jekuno Yes, that's the repository I forked. To get it working, all I had to do is pull the upstream etherpad-lite changes. If you're unfamiliar with git submodules, see [here.](https://gist.github.com/gitaarik/8735255)

**Comment by kfogel** [comment]
Since the repository mentioned above, https://github.com/inicio/ep_embedded_hyperlinks/, seems to have disappeared now, I'll add some information here for future searchers who happen to land (as I did) on this issue when looking for a way to have embedded hyperlinks in Etherpad.

I went to https://etherpad.org/plugins and searched for "links", and found the following:

* https://www.npmjs.com/package/ep_ice_hyperlinks
* https://www.npmjs.com/package/ep_linkify2
* https://www.npmjs.com/package/ep_embedded_hyperlinks2
* https://www.npmjs.com/package/ep_embedded_hyperlinks3
* https://www.npmjs.com/package/ep_add_hyperlink
* https://www.npmjs.com/package/ep_full_hyperlinks

There might be others, too!  I don't know, nor do I (yet) know what the differences are among the ones listed above.  But at least this is a starting point for anyone else looking for this feature.
