### ISSUE TITLE
eth.setHTML(padId, html) accent issue

### ISSUE THREAD

**Issue by javierpf** [ether/etherpad-lite#3184]
When a new pad is created and then use the setHTML method to include some text with accents (e.g. ción ción) shows like this
![image](https://cloud.githubusercontent.com/assets/740238/25751928/a7888740-3184-11e7-91c6-0194a61ef7c9.png)
When i edit the same pad, accents are accepted and saved correctly
![image](https://cloud.githubusercontent.com/assets/740238/25752107/41dd2a08-3185-11e7-8f93-4cc674bedca0.png)

**Comment by webzwo0i** [comment]
What database are you using? Looks like encoding issues. AFAIK using a browser seems to be okay, because internally all db-interaction is cached. When you are typing you see what you type. On reload you will be served data from the db cache if it is still there.

To be really sure the cache is cleared you need to restart the server. If I am correct, the first line in your second image should be wrong after that.

**Comment by javierpf** [comment]
After the refresh i can check that the first line in the second image has accents. The database stores it correctly. I'm thinking about the encoding of the request from the backend. There's a header in the API to set it as a parameter or something?

**Comment by cdparra** [comment]
We are still having this issue @webzwo0i Do you have any news on this?

**Comment by cdparra** [comment]
Any news regarding this issue?

**Comment by renebrain** [comment]
We have experienced the same problem on our side aswell. It is not only for setHTML.  It is also for setting the default text in the createGroupPad method aswell. We are using the Java API to connect with the node.js server. Can someone of the developer try to create a pad with one of those characters over the api and explain why this encoding issue happens? ö, ä, ü, ß

**Comment by lpagliari** [comment]
The problem is that the HTML need to be sent encoded to the API. The Ruby API does that (I'm not getting the same issues you are, so I was puzzled about that and started investigating), maybe the Java one does not.

Using `curl` without encoding:
```
curl "http://my.instance.com/api/1.2.13/setHTML?apikey=secret&padID=test&html=<html><head></head><body>ß</body></html>"
```
Result:
![image](https://user-images.githubusercontent.com/836386/27761502-813fb078-5e33-11e7-89c6-38e8673d3a66.png)

Now `curl` + encoding:
```
curl "http://my.instance.com/api/1.2.13/setHTML?apikey=secret&padID=test&html=<html><head></head><body>%C3%9F</body></html>"
```
Result:
![image](https://user-images.githubusercontent.com/836386/27761520-c03f7dc6-5e33-11e7-885f-151b4ee54954.png)

Hope this helps.

**Comment by kernelfreak** [comment]
Can anyone tell me what do you guys mean by encoding plain text before saving it in Java? Thanks.

**Comment by lpagliari** [comment]
@kernelfreak you don't need to save anything, you just need to transform the text you are sending to the Etherpad client. 

This should actually be handled on the Java client (more precisely [here](https://github.com/nilsfr/java-etherpad-lite/blob/8eeaf5f835190cd85981c5fcf183ade9b9b2415d/src/main/java/net/gjerull/etherpad/client/EPLiteConnection.java#L234)), but if you don't want to wait for them to fix it, you can handle the text encoding yourself:

```
import java.net.URLEncoder;
(...)
EPLiteClient client = new EPLiteClient("http://localhost:9001", "K8OF91QMQYUvrNu3e9rJ7FnnVgaB3m9q");
String originalText = "ö, ä, ü, ß";
String encodedText = URLEncoder.encode(originalText, "UTF-8");
client.setText("my_pad", encodedText);
```

**Comment by lpagliari** [comment]
@javierpf @cdparra are you using the Java client too?

**Comment by cdparra** [comment]
@lpagliari yes, we are using the Java client. I will try your solution Today and see if it works (I can trie to do it directly in the client code and then submit a pull request)

**Comment by lpagliari** [comment]
> I can trie to do it directly in the client code and then submit a pull request

Perfect! That would be even better. Thanks!

**Comment by cdparra** [comment]
Just tried this out and it works. I created a pulls request for the [java-etherpad-client](https://github.com/nilsfr/java-etherpad-lite/pull/8) I am using (not sure if there is another one)

**Comment by kernelfreak** [comment]
I encoded the text with URLEncoder.encode("text","UTF-8") and then it worked. Thank you.
