### ISSUE TITLE
Change default file storage directory?

### ISSUE THREAD

**Issue by h1k3** [ether/etherpad-lite#3226]
I'm so sorry to ask probably a very simple question, but where do I change the default file storage directory from /tmp/ on my server?

**Comment by rhelmer** [comment]
That sort of thing is generally set in `settings.json`, which is based on the `settings.json.template`: https://github.com/ether/etherpad-lite/blob/8bd8be97b98a69dce9768e5717c4f5ee0368ad1a/settings.json.template#L44

However this would be better to ask on the mailing list rather than an issue. If you feel like this should be documented better an issue for that would be welcome, however do note that it's already mentioned in the `README`: https://github.com/ether/etherpad-lite#fancy-install
