### ISSUE TITLE
Toolbar is not displaying for readOnly pad

### ISSUE THREAD

**Issue by vedantparchulkar** [ether/etherpad-lite#3273]
<p>Toolbar is displaying for editable pad:<br>
<iframe src="http://localhost:9001/p/Test" width=1200 height=600></iframe></p>
<p>But for readOnly pad toolbar is missing:<br>
<iframe src="http://localhost:9001/ro/r.e2ee5785e445672731c5de94e8558674" width=1200 height=600></iframe></p>

**Comment by lpagliari** [comment]
I cannot reproduce the error, @vedantparchulkar. The toolbar is showed with only some of the buttons for read-only pads, but it is still there. Can you post here what your read-only screen looks like, please?

**Comment by vedantparchulkar** [comment]
![image](https://user-images.githubusercontent.com/23275446/32179093-76a2ad88-bdb4-11e7-976e-5e5b9febaa41.png)

**Comment by vedantparchulkar** [comment]
Previously, I was using **readOnlyID** which I got using the API **getReadOnlyID(padID)**.
When I used the Readonly link from "Share this pad" option then the toolbar displayed properly with a read-only pad.

@lpagliari : Now, for readOnly pad Import/Export, Timeslider, Settings, Share and embed this pad, Show the users on this pad these options are displaying. I want to hide/disable Import/Export and Timeslider options for a readOnly pad. Is there any way to make enable/disable these options for readOnly pads?

Thanks in advance.

**Comment by lpagliari** [comment]
You can use `display: none` for those buttons, for example. There's a class `.readonly` added to `body` when pad is RO, so a simple CSS rule would address your needs. Does that help?

**Comment by vedantparchulkar** [comment]
Okay.. I am displaying a readOnly pad inside iframe so I will write a CSS code inside src/static/custom/pad.css. 

Is that right?

**Comment by lpagliari** [comment]
yep

**Comment by vedantparchulkar** [comment]
I made those changes but CSS is not reflecting. Restarted the ethernet. Still, CSS is not reflecting.
Am I missing anything?

**Comment by lpagliari** [comment]
> I made those changes but CSS is not reflecting. Restarted the ethernet. Still, CSS is not reflecting.

Can you post here your `etherpad-lite/src/static/custom/pad.css`?

> And one more thing, Is this a correct (secure) way to not allowing readers to use those hidden options from the toolbar?

No, it is not. You're just avoiding the users to see that these options are available, but if they know the path to use, they'll be still able to call them. To implement what you need in a safe way, you would need to submit a PR, because Etherpad does not differentiate between read-only and regular pads when rendering those options.

One thing you _can_ do is avoid displaying those options at all -- go to your `settings.json` and remove the commands you don't want to be displayed. If you need different behaviours for RO and RW pads, you may take a look on how those `toolbar` settings are used and go from there.

I hope this helps.

**Comment by vedantparchulkar** [comment]
@lpagliari Thank you very much for the explanation. It really helped.

Previously I had added CSS to the `root/src/static/custom/pad.css`

Now I have added CSS to `root/node_modules/ep_etherpad-lite/static/custom/pad.css`. It is working now.

Thanks once again.

**Comment by PythonHadoopMaster** [comment]
sadsads
