### ISSUE TITLE
dezalgo again

### ISSUE THREAD

**Issue by jeffrson** [ether/etherpad-lite#3328]
I'm posting a new issue, since other similar issues have been closed without a real solution. npm@4 is, unfortunately, no solution.

In `package.json` there is a dependency on npm 4.0.2 - if this dependency is replaced by npm 5.6.0 installDeps.sh works again.

**Comment by SeanShubin** [comment]
I managed to fix an error message regarding dezalgo by disabling the package-lock file.
I created a file named .npmrc in the src directory, with contents:
package-lock=false

This worked because in my case etherpad-lite started up fine the first time and would complain about delzago if I ever tried to restart it.  Probably not an ideal solution, but I am not familiar with the code base, I am just trying to get it to work.

**Comment by JohnMcLear** [comment]
I bumped dep reqs.   See if that helps.
