### ISSUE TITLE
Liberapay

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#3362]
I see you are already collecting donations though some platforms for this project.

Maybe you can consider using [Liberapay](https://liberapay.com/) to collect donations?
It is clearly a better alternative for free software than PayPal or so, and it is not just a one-time donation.

**Comment by JohnMcLear** [comment]
Happy to see a pull request for this @rugk 

One thing I will say is the problem we have isn't a problem of money, we have plenty of that!

We have a problem of finding someone with the right skills who wants to dedicate time to the project and can lead it going forward.  Funded or not, doesn't really matter!

Unfortunately none of the original authors have time due to travel/family/friends & other life commitments.  None of us expect this to change any time soon, we're all really sorry for that!

**Comment by JohnMcLear** [comment]
@rugk You are correct in your assertion however I have hundreds of people I already hire for my day job.  I don't fancy dealing w/ additional people on top of an already incredibly busy work/play life.  Hiring people has overheads.

Agreed there are barriers but Github imho makes it super easy for non-technical people to make these types of changes!  We might already have a Librepay account through SFC so I will bump Karen about that and ask her to respond to you.
