### ISSUE TITLE
How to set soffice (Libreoffice) template / export font

### ISSUE THREAD

**Issue by cataclysmic** [ether/etherpad-lite#3412]
I am trying to change the font that is used when exporting to docx and pdf.
The pad is set to Arial for alle styles and sizes but when exported Liberation Sans gets used.
I tried replacing the Default.ott template for LibreOffice to no effect.

Guess the parameters need to be send from the etherpad somehow but I have no idea where to start.

Any help is appreciated.

**Comment by JohnMcLear** [comment]
Yea see https://ask.libreoffice.org/en/question/172315/is-there-a-way-to-control-the-font-with-convert-to-txt-to-docx/

We convert HTML to Docx so maybe libre office supports font family properties for certain fonts?  IDK, but https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/LibreOffice.js#L46 is where you wanna be hacking.

It's unlikely we will bring this in as a feature though because each OS has it's own fonts and then each export util (abiword/libreoffice) will require different settings.  Adding support for this could end up being a LOT of code and all just to have a default font on export, not worth it!

One could argue that ep_font_family should be passing the font here btw, try that out and see if it works?
