### ISSUE TITLE
Etherpad won't work

### ISSUE THREAD

**Issue by c526537207** [ether/etherpad-lite#3443]
![_20180808101149](https://user-images.githubusercontent.com/31339057/43812367-92e8e8c8-9af3-11e8-99a2-7455d0c7c2f4.png)
When Linux starts, the following information appears.And cannot be opened in the browser.

**Comment by OnGle** [comment]
I'm not connected to this project in anyway however this issue is likely caused by attempting to start the etherpad server as the root user, if this is the case then this would almost certainly be intended behaviour. I'm not 100% sure how the permissions for etherpad are supposed to look like nor do I know your specific system configuration so don't take this as best practice and do some more research when/if setting up a production server, but try the following in bash.

```bash
adduser etherpad # create new etherpad user
# you'll be asked to fill in a password and possibly some other values, feel free to leave these blank
chown -R etherpad:etherpad <etherpad-install-directory> # overzelously allow all permissions to etherpad user
su etherpad # create a bash subshell with altered permissions
```
Afterwoulds in the same bash session start the etherpad server. If you no longer get that error then then this is a non-issue and it exists to prevent you from allowing a potential attacker administrator access to your server in the event they are able to break in through etherpad, this is standard practice in most tools on linux that don't require explicit root (administrator) privileges.

**Comment by c526537207** [comment]
@OnGle Thank you for your reply. The problem has been solved.
