### ISSUE TITLE
Server Requirements

### ISSUE THREAD

**Issue by MrMed** [ether/etherpad-lite#3470]
There's some guide for server requirements? I will make a server for etherpad for 5000 users and maybe, in the worst worst worst worst case, 100 users for pad. How can I configurate the server?

- How many cores?
- How many GB for RAM and ROM?

**Comment by muxator** [comment]
Hi @MrMed, sorry for the delay.

I do not really administer a super-large Etherpad installation, maybe someone else has more know-how on this.
In my experience Etherpad does not require many resources: 2 cores and 4 GB have been good enough for my, purportedly small, needs (with a "real" DB on another machine). In your case you could double the system requirements (4 cores, 8 GB) without being too hungry.

If we are talking about VMs, you could always scale up if needed.

Please give us some feedback about your experience, this would be helpful.

**Comment by JohnMcLear** [comment]
Tbh we don't document this is a lot because it "depends".  The biggest factor to consider is # of edits and # of users on a single pad at a given time.  Most instances live on EC2 micro instances and operate just fine.  We do provide load testing functionality and tools.  

https://github.com/ether/etherpad-lite/wiki/Load-Testing-Etherpad

It's really up to each site admin to test their expected users against given hardware to see how well it performs.
