### ISSUE TITLE
Export functionality update necessary

### ISSUE THREAD

**Issue by petrk94** [ether/etherpad-lite#3481]
Hello Etherpad Community,

Im facing currently a problem. My Hoster has switched from CentOS6 to CentOS7, now abiword is not longer available and soffice is consuming to much ressource to run for export.

Is there any alternative what can run without installing deep in the system? 
I dont have root permissions.

Thanks

**Comment by petrk94** [comment]
The problem is, my hoster doesnt want to install it due its not in the official CentOS7 repositories.
Thats why I need a alternative solution. I could run a CentOS6 Server at my hoster, but than I have to pay twice, only because I need one program for something like export functionality.

**Comment by muxator** [comment]
Hi,

your best line of action is probably negotiating a way of installing abiword directly with the administrator (since it seems that he has the ultimate decision about what can or cannot get installed in your server).

Depending on the technical limitations in your environment, you could try to compile Abiword from source as a static binary (there are some sources on the Internet).
Or you feel so inclined, you could also install abiword as a Nix package inside your home directory (technically fascinating, a bit more involved).

My best suggestion, however, remains exploring what is acceptable together with your administrator.

**Comment by petrk94** [comment]
@muxator
The admins at Uberspace gave their final decision, even after providing them the CentOS7 rpm pkg, they doesnt reacted on it. :/ 
Im really thinking about going to a Virtual Host, but for my projects I dont get money, and I want to save as possible, thats why Im using the shared host for 1€.

Do you can provide a link to a static binary? I have heard about Nix, but even have to get in.

**Comment by JohnMcLear** [comment]
Abiword is available on CentOS7, I run it for some clients.  It sucks tho.
