### ISSUE TITLE
EtherPad stucks when starting with pm2

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [ether/etherpad-lite#3484]
I am running EtherPad with pm2 as I am running multiple node.js instances on my server. However I fail to start EtherPad with pm2. Please help me figure out what is wrong.

## My command to start EtherPad with pm2
```
NODE_ENV=production NODE_USER=www pm2 start /path/to/install/ep_etherpad-lite/node/server.js -s /path/to/install/etherpad-lite/settings.json --name "EtherPad"
```

## Pm2 output with debug info
```
0|EtherPad | [2018-09-14 07:03:34.397] [INFO] console - Installed plugins:
0|EtherPad | [2018-09-14 07:03:34.405] [DEBUG] console - Installed parts:
0|EtherPad |
0|EtherPad | [2018-09-14 07:03:34.406] [DEBUG] console - Installed hooks:
0|EtherPad | <dl></dl>
```

**Comment by muxator** [comment]
This _may_ be related to #3466 (some files are created/looked for in a place that depends on the current working directory), which is present in **1.7.0** but should be fixed in the current development version.

Could you please try the current _devel_ to confirm if it fixes your issue?

Also, I did not understand if you are running multiple Etherpad instances at once on the same machine. 
If so, you may want to make use of the `--apikey` and `--sessionkey` configuration parameters (see [the documentation](https://github.com/ether/etherpad-lite#tweak-the-settings)) otherwise you may end up sharing secrets between different instances.

**Comment by Aster-the-Med-Stu** [comment]
Yup after the 1.7.0 release EtherPad works fine with pm2, the Advanced Node.js process manager. Thanks!

Besides, it is still worthwhile to note that if someone is trying to execute pm2 without setting the correct working path, it would throw error messages as follows:
```
Error: Cannot find module '/www/wwwroot/[redacted]/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Object.<anonymous> (/www/server/nvm/versions/node/v8.12.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
```
