### ISSUE TITLE
Assets workflow and optimizations

### ISSUE THREAD

**Issue by seballot** [ether/etherpad-lite#3505]
It may have been already discussed, but I would like to know why there is no assets optimization in etherpad? is it for a particular reason or just because of lack of ressources to implement it?

On a standard version of etherpad I have
![image](https://user-images.githubusercontent.com/17404254/47602211-ec47e500-d9db-11e8-82e7-e2beff2db82c.png)

None files are minimified, and we could concat them to reduce the number of queries.

It's even worst with #3441, because in order to get clean code, I have separated css files, but css does not support other files inclusions (SASS support it better), so there is a lot of tiny files loaded separately (and loaded twice, one time in the main page, one time in the editor iframe)

Could we implement a asset workflow, using gulp for example? I will be happy to do it

**Comment by muxator** [comment]
> why there is no assets optimization in etherpad? is it for a particular reason?

I think the best reason is that when Etherpad was first written (~2008) no such tools existed. Indeed, node.js did not exist yet! Etherpad was written in Scala and the JS part was the kind of javascript code you could expect from a Minimum Viable Product of that time.

When Etherpad was rewritten in 2011, the frontend code was left mostly untouched. Nodejs was in its infancy.

Over the years, the code was not adapted to the maturing ecosystem, and this brings us to the current status. Let's remember that, for its time, Etherpad Lite was a remarkable achievement. It just needs a lot of maintenance now :).

> Could we implement a asset workflow

I would love it. My usual conditions are: change one thing at a time, preserving stability and the current functionality.

> using gulp for example? I will be happy to do it

I would prefer Webpack.

**Comment by seballot** [comment]
After investigating a bit, I see that assets are already minified when settings "minify" is set to true. On beta.etherpad.org, "minify" is probably set to false, that's why assets was so heavy and numerous !

It could be a bit more optimized, concatenating the plugins files and the core files, but not sure this worth the effort, it does not seems to be a straight forward job.

So I prefer close this ticket, and spend time on the ep_tables2 which need a lot of fixs and improvements !

Btw, thanks muxator for the history, that's really important to know !

**Comment by lpagliari** [comment]
I'm reopening this, as currently my project is facing the same issue when loading our Etherpad instance:

![image](https://user-images.githubusercontent.com/836386/50017861-9099e100-ffb4-11e8-920a-c97cf4c7c53b.png)

I'll be glad to address this requirement, but I might need input from others using Etherpad, in order to not break other instances. I'm still collecting all steps that would need to be performed, but here is my initial list:

- [ ] build an initial (non-optimized) bundle with the JS files
- [ ] make sure we can debug errors in dev (use source maps?)
- [ ] make sure we don't need to restart the server to get the latest version of the files in dev
- [ ] include CSS files (maybe allow usage of SASS?)
- [ ] include fonts
- [ ] split the full bundle into at least 2 parts: an initial one with the "Loading..." part; and all the other files;
- [ ] allow assets to be minimized
- [ ] allow assets to be uglyfied
- [ ] allow development and production configurations
- [ ] allow instances to customize their bundle process (create a setting on `settings.json` to point to custom `webpack.config.js` files?)
- [ ] make sure plugins installed via `/admin` route are bundled too

Pending Questions
-----------------

- [ ] should we bundle each plugin separately?
- [ ] which browsers will we support? [Webpack is known for not supporting IE8](https://webpack.js.org/concepts/#browser-compatibility), so what would we do for those guys? Should we include a polyfill?

**Comment by lpagliari** [comment]
I know this is *a lot* to handle on a single PR, and I'm 100% with @muxator about preserving stability and not breaking existing functionalities. My plan is to submit a series of PRs.

**Comment by seballot** [comment]
Hi @lpagliari !
re "376 request 3.7Mb transfered"
Do you have the settings "minify" to true in your settings.json?
What plugins did you enabled to rich this value?
I know for example that the old ep_tables was using a very heavy library and only this plugin was like 1.2Mo (but now it's better, as I refactored it!). Maybe there is also some plugins like this...?

The number of request is also very high. My only guess is that you have the minified option to false, which makes load each piece of css separatly, instead of loading one concatenated file.

Can you investigate what are the mains requests (in number and in weight) ?

Thank you !

**Comment by lpagliari** [comment]
Hi @seballot,
That was just an example of my dev environment -- you are right, we don't have minification turned on there. But in production we do have, and the performance is still suffering. It is not too much about the size (in production the size is down to 2.0 Mb), it's more about the number of request that we need to make.

We have a highly customised Etherpad instance (we use 20+ plugins, for example, some with more than 15 files & other dependencies), that's why there are so much more requests than a clean Etherpad instance (without any plugin).

Do you see other solutions besides bundling the files together?

**Comment by lpagliari** [comment]
sorry, @seballot, it is a private instance and we cannot share it for now. But I really appreciate your offer, thanks!

**Comment by lpagliari** [comment]
OK, so after some work, we're finally able to release the first version of a plugin to optimize the assets we use: [ep_webpack](https://github.com/storytouch/ep_webpack).

It was getting too hard to bundle & manage Etherpad core files, so we started by bundling the assets on plugins only.

We were able to go from **411 requests down to 57** using this initial version.

From the initial list of requirements, we were able to address to following items:
- [x] build an initial (non-optimized) bundle with the JS files
- [x] make sure we can debug errors in dev (use source maps?)
- [x] make sure we don't need to restart the server to get the latest version of the static files in dev
- [x] include CSS files (maybe allow usage of SASS?)
- [x] allow assets to be minimized
- [x] allow assets to be uglyfied
- [x] allow development and production configurations
- [x] allow instances to customize their bundle process (create a setting on `settings.json` to point to custom `webpack.config.js` files?)

The idea was to _try to optimize as many plugins as possible, but leave the plugins that cannot be handled unoptimized_.

This is already enough for us, so I'm closing this issue.

**Comment by muxator** [comment]
I think we should start thinking again about this.

With current code, in particular, enabling `colibris` would skyrocket the number of HTTP requests for css files.

**Comment by seballot** [comment]
Hello Muxator ! The number of CSS request only get increased in dev environnement, in production, all colibris assets are concatenated into one (`pad.css`). 

Anyway, you would like to merge ep_webpack into etherpad core to improve assets?
