### ISSUE TITLE
Toolbar state not used for text entry? Bug or Intended?

### ISSUE THREAD

**Issue by dguillamot** [ether/etherpad-lite#3512]
I am able to select text, and change the color / font size / bold settings using the toolbar.  However, the toolbar state is not saved, and so when I continue typing, it is always default styling, color and size. 

Is this the intended behavior?

I really want the toolbar settings (Bold/Red/Size 18) for example to be set, saved in some kind of state, and applied to the text that I type after setting these in the toolbar.

**Comment by muxator** [comment]
Hi @dguillamot, you are right, this is the current behavior, and indeed it is deviates from how LibreOffice handles it.

Personally, I have never hit it, because I do not use any editor in that way, but I recognize that can be surprising to people accustomed to press the bold button, type something, and then deactivate "bold mode".

Currently there is no plan for supporting it, but PRs are welcome. If you feel so, please note that the actual behavior of LibreOffice (and other major editors such as MS Word, I presume) also takes care of some edge cases, that would have to be taken care of in the PR: when the user moves the cursor the bold button is deactivated, when it is pressed in the middle of a word it makes the whole word bold, and so on.

**Comment by JohnMcLear** [comment]
My plugins (IE ep_headings2) have this requested behavior but tbh it's not well implemented and given how Etherpad is written it's not super easy to implement knowledge of the caret location in "real time", afaik I had to use delays...
