### ISSUE TITLE
colibris: on mobile, horizontal scrolling is needed when showing line numbers

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3514]
When using colibris on a small screen, and the line numbers pane is shown, it is necessary to scroll horizontally in order to view the pad.

As explained by @seballot (colibris author), this is by design:

> I made it on purpose that the pad screen will be larger that the device screen.
> [...]
> WDYT with this behaviour?

I am trying to put myself in the shoes of a novice user here (maybe not even so literate in using computers).

On a small screen on Desktop I find it difficult to use.
I have to say that on mobile is easier because you can use your finger instead of the mouse to scroll.

In general, on mobile, I vote for not showing the line numbers pane at all (this is what the current skin does, btw).

Let's discuss here.

(I'm trying to upload an animated gif but I'm having problems with GitHub)

**Comment by muxator** [comment]
In case someone not familiar with the matter reads this, it's easier if I add a picture:

![small-screen-2018-11-15-ii](https://user-images.githubusercontent.com/4067621/48737063-548d8d80-ec4d-11e8-81fe-8d078b453501.gif)

**Comment by mrflos** [comment]
Hello, if I may suggest 2 classical behaviours  : 
 - option 1 (would probably need to write more code...) : on mobile and on small screens (let's says less than 600px) the line numbers and author disappear but on the bottom left or right, the information for current cursor position (line and column) could appear
 - option 2 : on mobile and on small screens (let's says less than 600px) the author info on the left disappears so that the line numbers are the smallest possible, like in [codemirror](https://codemirror.net/)

**Comment by seballot** [comment]
Option3 : line numbers and authors are hidden by default. Draging from the left to the right make appears them on top of the pad, like a classic menu opens on mobile. Finger mouvement can be tracked with library like hammer.js. I already made this for another project, but needs to import this library, and do some work

Personally now I'm thinking the best should be not display line numbers and author at all, like @muxator suggested. There is still the "cogs"+"show line numbers" for those who want to display line numbers

Option 1 is tricky because we need to make a pull request on ep_author_neat, and hope that the maintainer is still active etc...

**Comment by mrflos** [comment]
option 3 sounds great, but may also involve a lot of code to handle finger gestures..
the fourth option :)  to automaticaly hide the lines on small resolutions sounds good and simple

**Comment by seballot** [comment]
Great let's go this way !

**Comment by muxator** [comment]
@seballot, when you are ready... :)

**Comment by seballot** [comment]
Oh sorry, quite busy last days ! I will do it this afternoon, this is just few lines of code

**Comment by seballot** [comment]
Done !

**Comment by dessalines** [comment]
This appears to still be broken. Also, I've noticed I can't change the text style on mobile with this either, so no lists, headings, etc.

**Comment by seballot** [comment]
Hi @dessalines, can you please provide screenshots? 
https://beta.etherpad.org/p/test Works fine for me

**Comment by dessalines** [comment]
![img](https://i.imgur.com/HAY6ZTE.png)

The original: 

![img](https://i.imgur.com/M9vkwUX.png)
