### ISSUE TITLE
move the Dockerfile here

### ISSUE THREAD

**Issue by Trolldemorted** [ether/etherpad-lite#3524]
At the moment your Dockerfile resides in a separate repository and [clones this repo when building](https://github.com/ether/etherpad-docker/blob/master/Dockerfile#L23). Since docker uses overlayfs track container build stages this is a bad idea, could you consider moving the Dockerfile here and change the git clone command to [COPY](https://docs.docker.com/engine/reference/builder/#copy)?

We would gladly drop our own custom etherpad-lite Dockerfile and help improving the official one, if we can get features like persistency and smaller image sizes into the official builds.

**Comment by fcecagno** [comment]
Agreed, I do not quite understand why it uses supervisord, since as far as I understand, it's a node app, and that's it.

This is how we do it: https://github.com/mconftec/etherpad-lite/blob/mconf/Dockerfile
And this is our entrypoint: https://github.com/mconftec/etherpad-lite/blob/mconf/docker-entrypoint.sh
We use jq to be able to modify settings.json using environment variables.

Having the Dockerfile in the same repository enables us to enable automated builds more easily.

**Comment by muxator** [comment]
I agree. The Dockerfile has to be moved inside the main repository.

About configuring via environment variables: I have been thinking about it for some time now. Since it seems that this is a common use case, I have opened #3543.
