### ISSUE TITLE
API entry for exporting etherpad

### ISSUE THREAD

**Issue by kostaspa** [ether/etherpad-lite#3528]
Hello !
Can you please add an API entry, in order to export the data in the same format as the one that exists on the //<yourdomain>/p/<yourpad>/export/etherpad , but through the API? If this functionality already exists, please let me know and sorry for the false alarm!

Kind regards,
Costas and I wish you,
Merry Christmas!!

**Comment by lpagliari** [comment]
Hi @kostaspa,
I believe you're looking for the [`getHTML` API method](http://etherpad.org/doc/v1.7.0/#index_gethtml_padid_rev). If this is not what you're looking for, please let us know.

**Comment by lpagliari** [comment]
Hum, got it. Yeah, we don't have anything like that yet, as far as I know.

I've reopened this issue so we can keep tracking your request.

**Comment by kostaspa** [comment]
ok, to be honest im not in a hurry, cause i found another way to take this file, but i thought it would be nice implementation for the api and much more convenient.

**Comment by kostaspa** [comment]
@raybellis Yes, this is what am I doing, I am accessing the export url directly, but there is a cost for that, i have to create a user through the api that has access to the pad and after that, i am able to take the content. Despite that, the functionality already exists, so maybe it's not a big deal to add an entry, on the api. Other than that, i'm ok with that. Thanks for your interest!

**Comment by raybellis** [comment]
I've had a quick look, and the largest impediment to implementation is that the function that performs exports (`DoExport`) requires the HTTP `req` and `res` objects but the REST API handler doesn't pass those to the functions it calls.  I'm still considering what might be the best way around that.

**Comment by raybellis** [comment]
@lpagliari the easiest "fix" I can see is to have `API.handle` automatically add the `req` and `res` parameters to the `functionParams` array passed to every API call, after the `callback` parameter.  

Existing API functions would ignore the extra parameters, but it would then be possible to write an API wrapper for `DoExport` that would work.

What do you think?   If that approach is acceptable I don't mind having a go at it.

**Comment by lpagliari** [comment]
Sorry, guys, I won't be able to take a look on what you've proposed. I'm cc-ing @muxator, maybe he can...

**Comment by muxator** [comment]
Hi, sorry for being unavailable recently.

I was thinking if we can find a simpler solution. If I am understanding this correctly, what we want to do could boil down to return via an API call the value computed by [`ExportEtherpad.getPadRaw(padId)`](https://github.com/ether/etherpad-lite/blob/dfd45f0f5717248bb71636d9162e3c0b4a266428/src/node/utils/ExportEtherpad.js#L22).

Concretely, this could be made writing a simpler version of [`API.getHTML()`](https://github.com/ether/etherpad-lite/blob/727fbc26695e5d008dd849a5612da4ea33a9fc8a/src/node/db/API.js#L348) (without the `rev` parameter), where - internally - [`ExportEtherpad.getPadRaw(padId)`](https://github.com/ether/etherpad-lite/blob/dfd45f0f5717248bb71636d9162e3c0b4a266428/src/node/utils/ExportEtherpad.js#L22) is called instead of `exportHtml.getPadHTML()`.

In this way, we would not need to add optional parameters to each api call. Moreover, we could reuse the safety checks already in place for getHTML(), as I think there were a bit of security issues in the past (notice the use of `getPadSafe()`).

The change could be like this:

* Add `getEtherpad()` function to [db/API.js](https://github.com/ether/etherpad-lite/blob/727fbc26695e5d008dd849a5612da4ea33a9fc8a/src/node/db/API.js), which mimicks [`API.getHTML()`](https://github.com/ether/etherpad-lite/blob/727fbc26695e5d008dd849a5612da4ea33a9fc8a/src/node/db/API.js#L348) and internally calls [`ExportEtherpad.getPadRaw(padId)`](https://github.com/ether/etherpad-lite/blob/dfd45f0f5717248bb71636d9162e3c0b4a266428/src/node/utils/ExportEtherpad.js#L22) instead of [`ExportHtml.getPadHTML()`](https://github.com/ether/etherpad-lite/blob/dfd45f0f5717248bb71636d9162e3c0b4a266428/src/node/utils/ExportHtml.js#L29)
* Publish the function in [APIHandler](https://github.com/ether/etherpad-lite/blob/ce14a9960610cba75de7de7631eadafbbbe0a3be/src/node/handler/APIHandler.js), incrementing the API version
* Write some tests (like those in [tests/backend/specs/api/pad.js](https://github.com/ether/etherpad-lite/blob/3cedf474e5611e91f8cdf132999e385270d3ab50/tests/backend/specs/api/pad.js))
* Update the [documentation](https://github.com/ether/etherpad-lite/blob/fce55df2b7229cb61e5a0aeb7e07230f566f24c5/doc/api/http_api.md).

Comments are welcome.
I may still be unavailable for some time, but I would like to review a PR.

**Comment by raybellis** [comment]
@muxator if I understand correctly, what you propose would resolve my requirement to be able to export raw pads, but doesn't do anything to support exports in other formats, nor  fix the mismatch between the HTML output format from the API `getHTML()` call and a UI exported HTML pad.    The latter has the proper CSS template applied so looks much more like a pad as seen in the UI.

**Comment by muxator** [comment]
Hi, @raybellis, yes, my comment is limited to the scope of this issue (as per @kostapa's request).

**Comment by raybellis** [comment]
but @Kostapa's issue was getting nice HTML pads (in "export" format).   Exporting the raw `.etherpad` file was my use case for adding a more generic `exportPad()` API hook.

**Comment by muxator** [comment]
Ok I am confused now 😊

1. [This comment from kostapa](https://github.com/ether/etherpad-lite/issues/3528#issuecomment-449989579) made me think that he was the one asking for a way to export a pad in `.etherpad` format:

   > i need to download through the API, the exact file that is being generated from that link &lt;your_domain&gt;/p/&lt;padID&gt;/export/etherpad

2. regarding having a better HTML export, indeed the Export and the API seem to follow slightly different code paths. [`API.getHTML()`](https://github.com/ether/etherpad-lite/blob/727fbc26695e5d008dd849a5612da4ea33a9fc8a/src/node/db/API.js#L394) calls [`ExportHtml.getPadHTML()`](https://github.com/ether/etherpad-lite/blob/dfd45f0f5717248bb71636d9162e3c0b4a266428/src/node/utils/ExportHtml.js#L29), while [`ExportHandler.doExport()`](https://github.com/ether/etherpad-lite/blob/dfd45f0f5717248bb71636d9162e3c0b4a266428/src/node/handler/ExportHandler.js#L96) calls [`ExportHtml.getPadHTMLDocument()`](https://github.com/ether/etherpad-lite/blob/dfd45f0f5717248bb71636d9162e3c0b4a266428/src/node/utils/ExportHtml.js#L462), which is a wrapped version that adds  CSS styles. We could probably make those calls uniform.

Am I correct in thinking these should really go in two separate issues?
