### ISSUE TITLE
Keyboard shortcuts do not work in Firefox

### ISSUE THREAD

**Issue by theres-waldo** [ether/etherpad-lite#3621]
**Steps to reproduce**

  1. Load https://etherpad.org/ in Firefox.
  2. Click "Or Try a demo"
  3. In the demo, select a word and press Ctrl+B.

**Expected results**

The word becomes bold.

**Actual results**

The browser's bookmarks sidebar is opened.

Other shortcuts like Ctrl+I, Ctrl+U, Ctrl+Shift+L, Tab, and Shift+Tab are also affected. They all either have no effect, or perform an action in the browser UI.

This is a regression compared to a previous version of Etherpad which is deployed at https://public.etherpad-mozilla.org/, where the shortcuts work fine.

**Comment by muxator** [comment]
Hi @theres-waldo, what is your setup? This should have been fixed in **1.7.0**: see #3383 and #3413.

Indeed, at least on my home setup shortcuts are working fine (`CTRL+B`, `CTRL+I`, `Tab`, `SHIFT+Tab`, ...):
- Firefox **67.0.4**
- Linux (KDE, but does not matter)
- Etherpad **1.7.5** and current master (04a45fbe46a7). Also tested on https://beta.etherpad.org

**Comment by theres-waldo** [comment]
I can confirm that it works on https://beta.etherpad.org. It sill does not work in the demo in https://etherpad.org/. I guess that demo is running an older version, then?

**Comment by muxator** [comment]
Thanks for making me notice!

I guess you are referring to the "try a demo" button in the homepage. This is a case of becoming selectively blind on my part. That button should be removed: the demo in standstorm is probably unsupported since forever (certainly well before I started working on Etherpad).

Thanks again.

**Comment by theres-waldo** [comment]
Ok, thanks for clarifying!

I guess we can close this issue, then, and I just need to get the installation I care about (http://pad.mozilla.org/) to upgrade to >= 1.7.0.

**Comment by muxator** [comment]
Removed the demo button with https://github.com/ether/ether.github.com/commit/f71c18a729d6.
