### ISSUE TITLE
White text for dark colors

### ISSUE THREAD

**Issue by wraybowling** [ether/etherpad-lite#3641]
If a user sets their color darker than ~50 luminance, their messages in chat need white text in order for their messages to remain legible. This wouldn't cover fully accessible color contrast of 4.5:1, but we also want All The Colors, so whatever.

**Comment by JohnMcLear** [comment]
I thought we already had that functionality, guess not..  we do have it for the pad text though so it should be copy/pasta job.

**Comment by orblivion** [comment]
I started looking at this one.

**Comment by JohnMcLear** [comment]
+1 tnx @orblivion

**Comment by orblivion** [comment]
Hey, I'm gonna step away from this (and other issues) in case someone else wants to take a look.

(@JohnMcLear I alluded to this over email, though I'm not sure if I'm reaching you. Please let me know if there's some technical issue there.)

**Comment by JohnMcLear** [comment]
@wraybowling There absolutely is a technical issue there.  I replied like 5 times :D

**Comment by JohnMcLear** [comment]
Jump on here: https://video.etherpad.com/p/orb

**Comment by JohnMcLear** [comment]
@wraybowling Just FYI @orblivion is gonna work on this and be funded by the Etherpad foundation :)  That's what the whole video call was about :) 👯‍♂

**Comment by orblivion** [comment]
Yep, sorry for the confusion! Had a spam folder issue :man_facepalming:.

**Comment by orblivion** [comment]
Just a quick update. I'm still investigating, but it seems to be an issue of CSS importance hierarchy. The value should be getting set here along with the doc text color:

https://github.com/ether/etherpad-lite/blob/e6251687bf6f0d773ef5cd8883465d67e18f4816/src/static/js/ace2_inner.js#L274

But it has no effect. Setting `parentAuthorStyle.backgroundColor` elsewhere in this function works properly. I more or less replicated this in the console. So there's something special about the `color` attribute in the chat text. I'm gonna investigate css files next.

**Comment by orblivion** [comment]
# Overview

Per @JohnMcLear 's suggestion I'm going to step away from this after having looked through it for a few hours. Here's what I can conclude:

This issue only exists when using the Colibris skin. The relevant lines of CSS (more on this below) were added in #3496 PR by @seballot . Perhaps if he's available he could give some guidance here.

# How white text for dark backgrounds is set

This line would be setting the color of the chat text to white if not for css issues (described below):

https://github.com/ether/etherpad-lite/blob/e6251687bf6f0d773ef5cd8883465d67e18f4816/src/static/js/ace2_inner.js#L274

Indeed, this line is responsible for successfully setting the _background_ color of the same chat text, even in Colibris:

https://github.com/ether/etherpad-lite/blob/e6251687bf6f0d773ef5cd8883465d67e18f4816/src/static/js/ace2_inner.js#L268

Now, the variable name `parentAuthorStyle` doesn't particularly sound like it's supposed to apply to the chat text. But I'm assuming it is because I've observed that it does.

# The CSS issue

In CSS for Colibris, the font color for both document text and chat text are set here:

https://github.com/ether/etherpad-lite/blob/d3f583c9c5919aa61f10d476810d429d3767b5ae/src/static/skins/colibris/pad.css#L57

Chat text color has a very **specific selector** here:

https://github.com/ether/etherpad-lite/blob/d3f583c9c5919aa61f10d476810d429d3767b5ae/src/static/skins/colibris/pad.css#L40

And a more **general selector** here (possibly among other general selectors):

https://github.com/ether/etherpad-lite/blob/d3f583c9c5919aa61f10d476810d429d3767b5ae/src/static/skins/colibris/pad.css#L28

The selector we use in jQuery to change it to white, as far as I can tell, is `".authorColors .author-a-..."`. My observation is that this doesn't work in Colibris because it is not specific enough to override the **specific selector** in the CSS file,  _if and only if_ the `!important` is there. By contrast, the document text color, which does not exhibit this bug, is set by the same CSS rule with `!important`, but it does not have such a specific selector.

## Possible fixes

With that in mind, here are a few things that I can think of that, per my observations, could work in principle:

* Remove the **specific selector** for chat text and time.
  * Per my observations, this causes no problems because it's still caught by the **general selector**. However there may be some unintended consequences.
* Remove `!important` from the rule
  * Very likely to have unintended consequences
* Make a new rule only with the **specific selector** that doesn't have `!important`
* Within Javascript, [overwrite `cssText`](https://stackoverflow.com/a/1986850) to add `!important` via jquery
  * This is pretty bad because it deletes all the other style. We could work around this but it's clearly a hack at that point.

Since CSS is so precarious I'd rather leave the call to someone more familiar with this theme.

**Comment by seballot** [comment]
Hi @orblivion ! thanks for investigation, and sorry if I broke this functionality. I will have a look today

**Comment by seballot** [comment]
Hi, just fixed it inside #3744
