### ISSUE TITLE
Etherpad image on quay.io

### ISSUE THREAD

**Issue by pierreprinetti** [ether/etherpad-lite#3669]
@muxator
If you think it's a good idea, please send me your quay.io username so that I can add you to the fresh new [quay.io/etherpad](https://quay.io/etherpad) organisation team. You'll then be able to create an automated build pipeline.

Quay is the Red Hat alternative to hub.docker.com, based on the opensource [quay project](https://github.com/quay/quay).

Otherwise, please let me know and I'll delete the organisation (and release the name!).

**Comment by muxator** [comment]
Hi @pierreprinetti, thanks for the info.
It's **muxator**, the same as my username here.

BTW, the site dos not work with Firefox Enhanced tracking protection (due to Google Captcha, I suppose).
Similarly, an intermediate redirect for the Oauth login via github fails with an (ugly) HTTP/4XX under the same conditions :)

**Comment by pierreprinetti** [comment]
You have the invite! Closing this, you will proceed with time & opportunity.
