### ISSUE TITLE
CentOS 7 config doesn't set environment vairable for production

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3724]
```
Environment="NODE_ENV=production"
```
In startup service config doesn't work.

```
Mar 16 22:42:38 JohnEtherpad run.sh[39231]: [2020-03-16 22:42:38.243] [WARN] console - Etherpad is running in Development mode.  This mode is slower for users and less secure than production mode.  You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
```
Mheh, to get things moving I did..

```
NODE_ENV=production exec node "$SCRIPTPATH/node_modules/ep_etherpad-lite/node/server.js" "$@"
```
as bottom line of bin/run.sh

**Comment by muxator** [comment]
From where was this snippet taken?

```
Environment="NODE_ENV=production"
```

It seems a fragment of a systemd unit.

**Comment by JohnMcLear** [comment]
Google searching for CentOS 7 etherpad production returns

https://www.certdepot.net/rhel7-install-etherpad/

I tried ``Environment=NODE_ENV=production`` first but that syntax is wrong.

**Comment by JohnMcLear** [comment]
Perhaps related to 


Environment and EnvironmentFile set the variables, usable by the unit, but like the sh command, does not export it to child processes. For that, you also need to list it in PassEnvironment, just as you would with the export shell command. See the systemd documentation on EnvironmentFile and PassEnvironment

Also, note that the contents of an EnvironmentFile is not a shell script, but key-value pairs that look rather too much like sh, so naming it with a .sh extension is misleading.

Source: https://serverfault.com/questions/828999/systemd-environment-and-environmentfile-not-working

**Comment by muxator** [comment]
Even if I think we might, as of today we do not release an official systemd unit file (yet).

Personally, I would not use that unit file in production (at least I would put limits on the restarting policy).
Anyway, I tried it on Ubuntu 19.10 (systemd 242), and the `NODE_ENV=production` variable is correctly interpreted. I guess (but did not try) that it would be the same under Centos 7, that unit file is not using any particular systemd features.

Your problem was probably somewhere else.

**Comment by JohnMcLear** [comment]
Yea Ubuntu is fine, It's defo a CentOS issue.  It's documented here at all :D  I can ask the sysadmin to try figure it out.
