### ISSUE TITLE
[Docker] Setting Static API Key?

### ISSUE THREAD

**Issue by jkaosw** [ether/etherpad-lite#3849]
I'm attempting to set up an instance of Etherpad in Kubernetes to be embedded by one of our applications.

However, upon doing a quick test for reliability/availability on Kubernetes, when destroying and redeploying the Etherpad pod, it respawns with a new API key in the APIKEY.txt file.  We don't intend to have high availability in terms of having multiple replicas, but having the API key change upon restart seems not so great.

Is there any way to force an Etherpad container to spawn up with a set API key currently?

**Comment by JohnMcLear** [comment]
Afaik you just set it in ``APIKEY.txt`` in the root folder before running it for the first time?

I could be wrong...  It's been a long time since I touched that logic.

**Comment by jkaosw** [comment]
Interesting.  I'm just curious how that logic works.  Does Etherpad check that file to verify the APIKEY? If so, mounting a ConfigMap over it would be fine and we could just run for that.

I will test tomorrow and put findings here.

**Comment by JohnMcLear** [comment]
Afaik yes.  But this is code I wrote X years ago, it may have changed and I'm too lazy to look :)

**Comment by muxator** [comment]
@jkaosw, when Etherpad starts, it looks for `APIKEY.txt` at the root of its installation (the basedir of the repo).

You can see this in the logs at startup time:

```
[2020-04-09 01:35:42.366] [INFO] APIHandler - Api key file read from: "<base>/APIKEY.txt"
```

If that file does not exist, it is created with random contents:
```
[2020-04-09 01:36:02.122] [INFO] APIHandler - Api key file "<base>/APIKEY.txt" not found. Creating with random contents.
```

If you do not like the directory where `APIKEY.txt` lives, you can pass the `--apikey` parameter at startup with the full path to an arbitrary text file:

```
node <BASE>/node_modules/ep_etherpad-lite/node/server.js --apikey /somewhere/NAME_OF_APIKEY.EXT
```

The default location will be overridden and not looked for. All the rest will stay the same.


The code that implements this functionality is here:
https://github.com/ether/etherpad-lite/blob/df08883a009aeaebfbe59a53c592ac25cd3aff06/src/node/utils/Cli.js#L48

**However**, in Docker:

Currently, there is no support for passing command line arguments in the official Dockerfile:
https://github.com/ether/etherpad-lite/blob/df08883a009aeaebfbe59a53c592ac25cd3aff06/Dockerfile#L53

And you will not be able to use an ENV var for setting the apikey location, because that functionality is only supported for the config file (`settings.json`), while `--apikey` is command line only.

**If** it works for you, you could **bind mount just the `APIKEY.txt` file** at its current location (the base path, `/opt/etherpad-lite` in the official Docker image). I do not know if it is feasible under Kubernetes.

Otherwise a PR is welcome :)

**Comment by jkaosw** [comment]
@muxator Thanks for the hints and the information!

I am utilizing Vault in my environment so I injected the APIKEY directly into a file (/vault/secrets/etherpad/APIKEY.txt) and then referencing that file by utilizing a 'command block' for the container specification.  YAML for the deployment looks like the following:

```containers:
      - name: etherpad
        image: etherpad/etherpad
        command: ["node", "node_modules/ep_etherpad-lite/node/server.js", "--apikey", "/vault/secrets/etherpad/APIKEY.txt"]```

Seems to work like a charm.  Thanks for your help. :)

**Comment by Dherlou** [comment]
TLDR for future readers, because it is not documented in the [docker.adoc](https://github.com/ether/etherpad-lite/blob/develop/doc/docker.adoc) yet:

From v2.0.2 onwards it is sufficient to add the following to your `docker-compose.yml` to reenable legacy apikey authentication with a static API key. If you want to use a dynamically generated API key, omit the `volumes` part.
```yml
services:
  app:
    environment:
      AUTHENTICATION_METHOD: "apikey"
    volumes:
      - "<host-path-to>/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt:ro"
```
