### ISSUE TITLE
Usage of google fonts not GPRS-compliant

### ISSUE THREAD

**Issue by Franz-Heinz** [ether/etherpad-lite#3867]
it seems that etherpad loads fonts from googles servers by default. This is a problem for usage in Europe, because there is no confirmation or even notice for users IN ADVANCE.

To me it seems, that the problem lays in **/src/static/css/iframe_editor.css** and **/src/static/css/pad.css**.

**Comment by JohnMcLear** [comment]
Err, yikes.  I do not remember doing this...   This is a big time no no from a privacy perspective and from a bundling perspective...  I'm testing against ``develop``

I looked in iframe_editor.css and don't see it.  In fact I see the fonts locally: https://github.com/ether/etherpad-lite/blob/develop/src/static/css/pad.css#L1287

I also changed font and didn't see any calls to any external resources..

Are you sure about this @Franz-Heinz?

I'm gonna close this but if you can show me where Etherpad is making ANY external calls what so ever please do let me know because that would be a cause for concern.

@Franz-Heinz for future contributions please read https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/ prior to submitting a bug report.

Thanks for reaching out.
