### ISSUE TITLE
Own icon is not displayed in the pads themselves

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3875]
Hi everybody!

index page
<img width="169" alt="Screenshot at Apr 17 16-01-19" src="https://user-images.githubusercontent.com/25965602/79572067-fb858b80-80c4-11ea-98a2-2d06b9da963b.png">
pads page
<img width="260" alt="Screenshot at Apr 17 16-13-05" src="https://user-images.githubusercontent.com/25965602/79573029-a34f8900-80c6-11ea-9d5c-90373f3dfdfd.png">
credentials.json
```
{
  "favicon": "https://other-site.com/favicon.ico",
  "ip": "127.0.0.1",
  "trustProxy": true
}
```

Cache cleaned, did not help.

**Comment by JohnMcLear** [comment]
Hrm, will test..

**Comment by JohnMcLear** [comment]
Yea confirmed, the favicon stuff needs a rewrite.  It's an easy fix.

 - [ ] URLs wont work.
 - [ ] The location of a new favicon is not specified, it should be.
 - [ ] The Settings.template.json file is kinda lame at describing things.
 - [ ] Test with / without skins.

I created a PR showing where needs to be worked on.  I'm not going to work on this because it's an ideal low hanger.

**Comment by muxator** [comment]
> I'm not going to work on this because it's an ideal low hanger.

Agreed. @alekso87, would you like to give it a try? That could help us.

**Comment by aryamanpuri** [comment]
Hi @JohnMcLear 
Can I give this issue a try?
Would you like to give a brief about this issue and how to counter this issue?

**Comment by JohnMcLear** [comment]
Just read the issue.  It's all there.  Try replicate and if you can then fix.

**Comment by JohnMcLear** [comment]
@HP-bit How are you doing?
