### ISSUE TITLE
[Display bug] Italic type overlapped by authorship colour at transition

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/etherpad-lite#4013]
## System

OS: Win 8.1/Win 10
Browser: Firefox 76 / Chrome 81
Ehterpad version: 1.8.4

## Problem description 

Some characters are overlapped by authorship color at the transition from italic to normal formatting

![grafik](https://user-images.githubusercontent.com/44228345/82048025-23601300-96b4-11ea-96d4-2b02fc4c950a.png)

**Comment by seballot** [comment]
ah ah, nice found, you have good eyes !!

I'm not sure we can do anything. Maybe if we load the Italic font (instead of letting the browser simulate it) it will work better, but that will be an additional load (we already load Regular and Bold fonts), and anyway for quicksand there is no Italic font.

I would say leave with it, of with `ep_author_neat` ;)

Also it does not do this if same author type `italic normal` and then put the word italic in italic, it need quite a combinaison of event to happen :)
