### ISSUE TITLE
Question: How to get the last text added 

### ISSUE THREAD

**Issue by joassouza** [ether/etherpad-lite#4015]
Hey Etherpaders,
I've been struggling to find a way to implement a feature that highlights every user edition after entering in a "suggesting mode". I didn't find a way to have the information of the new text added to apply the an attribute only on this part.
What do you guys recommend to achieve it?

What I've tried:
1. Setting an attribute on `contentCollectPre`, but this applies the attribute on all line or all span (it does not get only the part edited).
2. Clear the Authorship [1] of the all document and use the hook `aceSetAuthorStyle` to apply a special color for every author [2]. This is hacky and kinda works, but on long documents takes over 20 seconds to process the step [2] and the browser gets unresponsive as well. To [2] takes effect I need to reload the editor.

An example of this feature on Google Docs

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4945372/82060029-2c91b580-969d-11ea-95c0-04832e5aaea8.gif)

_I know this is not the best place to ask questions, as this is not a Etherpad issue per se. Sorry if I'm breaking any rule_

**Comment by JohnMcLear** [comment]
I don't really understand this feature request / ask.  I get that you want to implement it, but why would you want the font to turn to the color of the author?  Is this instead of having the background color representing the users edit?  Is it just to show where a user is editing?  I fail to see the purpose so sorry I'm not sure what the end goal is:???  Sorry for being dumb.

**Comment by joassouza** [comment]
Hey @JohnMcLear, thanks for you response. In our use case the main purpose is to track an "other user" editions to make to possible check what it has changed since the pad became available to revision. It's like the same workflow of _reviewing a pull request_. 
That's an example of the feature we want to replicate in other software 
https://youtu.be/anTBLCkBaaA?t=81

**Comment by JohnMcLear** [comment]
Holy crap that's a horrible UX 🗡️ 

I can see why you want to fix it..

So stupid question, but are you familiar with the Timeslider?  I "think" you just wnat to see what edits user Y has made since point X in time?  Why not just make timeslider only show edits from X rev and only follow Y user?  

Their UX is horrible, don't do that, please.

**Comment by JohnMcLear** [comment]
Just to add to this, I swear I made something that "tracked a specific author", but essentially doing that is really easy, just check contents for spans with authorID of *whatevz and if they are changed ``scrollTo`` those edits, you can them watch them like a "movie" or whatever, basically tracking them as they happened in *real-time in the pad.

*real time is relative to revs to pad so also includes time of inactivity for an author...

Please do correct me if I misunderstood, the video was verbose and perhaps I missed some points/got confused by the UX...

**Comment by joassouza** [comment]
I couldn’t agree more, their UX is horrible. Thanks for you help Jhon. I’m gonna try something on that direction 👍🏽
