### ISSUE TITLE
Tab indent affects whole line number

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/etherpad-lite#4028]
Indent via tab / shift+tab always moves the whole line number (even if text goes over several lines) to the left / right. 

Sometimes it would be useful to just shift the text from the point where the cursor is set. Bullet points / whole line number could be just moved when the cursor is directly on the right of a bullet point. Doing so, it would be possible to arrange kind of tables. What do you think?

**Comment by JohnMcLear** [comment]
I have been working on lists for the last 2-3 months and they are due a large refactor.  @muxator is reviewing for 1.9.

Really though, I don't understand what you mean with your question.

cursor !== caret.  I think you are talking about the caret?

If you want tables, use a table plugin!

Can you include some pictures with your question so I can understand it?

**Comment by JohnMcLear** [comment]
Oh I see what you mean.  Yea, the current behavior is desired behavior.

The long and short is that a "tab" doesn't exist in the HTML world, the closest is ``&emsp;``.  Because of this anything we implement would be a *hack* and probably cause more heartache than solve problems.

Obviously a plugin could do this, catch ``rep.selStart`` and ``rep.selEnd`` and if it's ``[x,0]`` then do tab else insert some spaces.  There would be no way to make multiple lines align though, this is not feasible in HTML afaik...  But I could be wrong!

**Comment by Oremountainflorian** [comment]
@JohnMcLear I meant caret, sorry for that! 

Ok sounds reasonable and it's fine as it's desired behaviour. Isn't worth any headache as you said... 

The thing is the tables plugins aren't working anymore under the new etherpad version (see here https://github.com/seballot/ep_tables2/issues/35). So I thought this could be kind of an easy workaround but it isn't as we see here

Thanks for your detailed explanation!

**Comment by JohnMcLear** [comment]
I'm sure ep_tables will get a fix :)
