### ISSUE TITLE
Tabs in monospaced font are rendered with strange width

### ISSUE THREAD

**Issue by ThomasWaldmann** [ether/etherpad-lite#444]
On beta.etherpad.org i tried to edit some piece of python code:

```
class Foo(object):
    pass
```

I used monospace font, indented "pass" by pressing the tab key.

Expected behaviour: visual indentation by some definite amount of char positions. Perfect would be 4 as this is the standard in python (and also a useful amount for other purposes).

Experienced behaviour: it looked like it was indented by about 3.5 times the width of a char.

I could not get the same width of whitespace by pressing the space key multiple times.

Suggestion:
a) render tabs as wide as 4 blanks (font issue?)
b) alternatively, EXPAND a tab keypress and insert 4 blanks into the text (python coders would love you for that)

**Comment by PanderMusubi** [comment]
This bug is also in the version currently in use by etherpad.mozilla.org when using unordered lists (bullets with indentation). As https://github.com/ether/etherpad-lite/pull/1532 is fixed, could fixing this issue also move forward?

**Comment by JohnMcLear** [comment]
@PanderMusubi etherpad.mozilla.org is 10's of thousands of commits old so should not be used.

**Comment by PanderMusubi** [comment]
Ha! Well I hope this encourages them to upgrade. For those on etherpad.mozilla.org, see https://bugzilla.mozilla.org/show_bug.cgi?id=1173329

**Comment by superawesome** [comment]
More accurately, etherpad.mozilla.org is a different codebase entirely- it's not Etherpad Lite, it's the original Etherpad (java/scala). We haven't switched over due to lack of team site support in Etherpad Lite.

We've considered switching anyway, but that's a huge feature that we've come to enjoy, and we haven't had the engineering time available to replicate it (apart from "use Google Docs instead"). We may eventually stand up a separate, standalone Etherpad Lite instance and push users to do exactly that.

**Comment by JohnMcLear** [comment]
@superawesome We do provide some team pad support through plugins and there is an active project called MyPads which is bringing full support (assuming you want to replicate the old behavior). 

Other organizations have been active and have implemented team site support successfully.  The real problem here is Mozilla haven't been participating in Etherpad.  I kinda get how things work at Moz so I assume no one took the lead so it kinda got left to no-one to organize/converse with us.

We'd very much like to have Mozilla back on-board and back on the project, maybe you can take the lead on it?

FWIW The Webmaker team are "supposed" to be doing Etherpad related stuff but they went dark in January...  https://github.com/MozillaFoundation/plan/issues/244

**Comment by PanderMusubi** [comment]
I hope Mozilla can move forward with this. Perhaps Mozilla can put out a call for volunteers on https://etherpad.mozilla.org/ and on all the team sites to help out with upgrading/migrating? I think most of the users would like to benefit switching to Etherpad Lite.
