### ISSUE TITLE
Include Author when Importing a Document

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4504]
When importing a file, the generated changeset's meta data do not contain an author, ie no author is set for the changeset that clears the pad and inserts a newline nor the following changeset that imports the new text.

Both should be set to the author that is doing the import, right?

**Comment by JohnMcLear** [comment]
Should be but also imports via API might not include an author do be mindful of that.

**Comment by JohnMcLear** [comment]
Been present from at least 1.8.3

**Comment by rhansen** [comment]
My preference would be to use the author ID of the author doing the import for the clear everything change and the import change. When importing `.etherpad ` files it would be nice if the original author IDs were preserved, but there's a problem: preserving authorship means users can impersonate other users.

**Comment by JohnMcLear** [comment]
I spoke to a few clients who use the import feature on every pad they create, they don't consider this a bug but a feature..

But I'm w/ @rhansen from a technical perspective..  I think this is a feature request, not a bug tho, because this behavior has never existed despite it being the *right* way of doing things to ensure document author integrity..
