### ISSUE TITLE
Attempting to restart server using /admin/settings hangs instance

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4546]
Caused by https://github.com/ether/etherpad-lite/commit/a000a93dc644aa32f5ad9a0385837981f57edc44#diff-e0209b1fab75aa27962acd6cac97eeaa8fd2f41a4e61d4cd0b913d1206b1f7d0R61

Replicate by click Restart in /admin/settings

Server will restart after all tabs/windows are closed...

Noticed bug due to not being able to update plugins using admin interface.

**Comment by webzwo0i** [comment]
Currently we only call cancel, so no new connections are allowed, but the remaining connections stay alive.
The fix is imo something like (not sure if something special needs to be done for socket.io's websocket):
- store sockets that connect ('connection' event)
- on restart/ctrl+c in the console, call `cancel` to stop new connections
- call the `end` method on all sockets, to send a TCP FIN
- wait for some time (e.g. some seconds, maybe less on ctrl+c) to give the clients the opportunity to gracefully terminate the sessions, then call `destroy` on every remaining socket
