### ISSUE TITLE
Electron app for desktop usage

### ISSUE THREAD

**Issue by madmath03** [ether/etherpad-lite#4628]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but more of a use case I thought about : how to edit etherpad files locally ?

**Describe the solution you'd like**
My idea would be to package the Etherpad website as an Electron application, kind of like draw.io does:
* <https://github.com/jgraph/drawio-desktop>

**Describe alternatives you've considered**
Installing a web server locally to run Etherpad... kinda complicated for non technical users.
Having a binary would be more user friendly and could be deployed anywhere (Windows, Mac, Linux, ...)

**Additional context**
NA

**Plugin?**
NA

**Comment by JohnMcLear** [comment]
Would love to see this.

**Comment by rhansen** [comment]
I think this only makes sense if Etherpad is morphed into a file-centric editor that happens to have a collaborative editing feature. Right now the main point of Etherpad is collaborative document editing, so a standalone desktop app doesn't make much sense. Or do I misunderstand the request?

**Comment by JohnMcLear** [comment]
Sometimes I'm on a flight and have to spin up an instance in a VM just to access a pad.  Even if I still have to spin up an instance, doing so "behind" the scene and having what is a specific app (albeit just we view) would feel optimal from a users perspective.

Essentially the app would start an etherpad instance (if one doesn't already exist) and serve local content to a web view).  It would also serve as persistent state/memory of previously edited pads and potentially could provide an easy sharing mechanism that doesn't require port forwarding (think RTC)

**Comment by kzamore** [comment]
May I offer an alternate solution?  Everything you are describing is an etherpad client.  Rather than moving electron into the etherpad-lite project, how about creating a new project named etherpad-desktop which utilizes the server's API to access pads.  The client can manage offline settings itself.  Obviously this is not a core feature enhancement that the ether team wants to create, so maybe there is value in mocking up an electron app and then presenting a support path moving forward so it could become an official ether app.

Just my $0.02 as a lurker

**Comment by JohnMcLear** [comment]
@kzamore did you try this approach?  Happy to see a repo if you find it works for you :)

**Comment by JohnMcLear** [comment]
Closing as stale.

**Comment by sheeepdev** [comment]
I would love to see this :(

**Comment by bbernicker** [comment]
I would also like to see this, but I would not know where to start in developing it.
