### ISSUE TITLE
Socket.io connection error appears after browser window opened for a extended period of time

### ISSUE THREAD

**Issue by gstratford** [ether/etherpad-lite#4630]
**Describe the bug**
We have several users of EtherPad that leave documents open for an extended period of time (often overnight) and return to the following error message:

"Error: socket.io connection error: {"type":TransportError", "description":{"isTrusted":true}}≈ at https://urlredacted.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a9be1ce5 at line 225"

**To Reproduce**
1. Create new Pad
2. Enter pad text
3. Leave open for over 2 hours
4. Return to browser window to see error

**Expected behavior**
Return after extended period of to pad in browser with no error 

**Screenshots**
![image](https://user-images.githubusercontent.com/2601521/103686151-3d9c7900-4f43-11eb-829b-4c610eb11b0f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15
 - Browser: Safari
 - Version: 14

**Additional context**
We are running EtherPad Lite on a Ubuntu 18.04 (LTS) x64 with Nginx as a reverse proxy. No plugins installed in Etherpad

**Comment by JohnMcLear** [comment]
Session timeout?  Is it possible to extend in settings?  

We are looking to migrate away from socketio so I don't want to go too far into this.

**Comment by webzwo0i** [comment]
I also sometimes see this error during testing and could not reproduce yet. The pad.js line is in the reconnect code, but we should have coverage for part of reconnection logic already.

Please ensure that the instance is not restarted (that should be visible from the output of the instance). In case you can reproduce this it would be nice if you could go to a pad that you want to keep open and write `localStorage.debug = '*';` into the developer console. Then, when the error happened, export the log messages, search for "error" and paste the lines before.

**Comment by gstratford** [comment]
@JohnMcLear Is this the setting you are referring to in the configuration file? 
<img width="432" alt="Screen Shot 2021-01-05 at 1 33 00 PM" src="https://user-images.githubusercontent.com/2601521/103701304-a17e6c00-4f5a-11eb-93ab-3ff78fdbbde2.png">

**Comment by rhansen** [comment]
> @JohnMcLear Is this the setting you are referring to in the configuration file?

I think John is referring to `validUntil` in [`createSession()`](https://etherpad.org/doc/latest/#index_createsession_groupid_authorid_validuntil). Are you using the HTTP API? Even if you are I don't think it's caused by session expiration because that should pop up a different error if I recall correctly.

My current guesses:
* Right now [the client sets `reconnectionAttempts` to 5](https://github.com/ether/etherpad-lite/blob/3373f059e6ee74bfeb9b52f77edc541be86b717a/src/static/js/pad.js#L223). Maybe that is being exceeded for some reason, though that should cause a `reconnect_failed` event, not `error`.
* A NAT or firewall device is expiring connection state due to inactivity. (Though the server should be sending a socket.io ping every 25s to prevent that from happening.)
* The browser is killing the connection to save resources because it thinks the tab is inactive.
* The interface is being deconfigured for some reason. Perhaps the machine is suspending, or maybe the DHCP lease is expiring before the OS renews it, or maybe the OS is powering down the interface to save power.

The server log should have an entry that corresponds to the red pop-up. When does that appear? Right when you return to the computer?

What version of Etherpad?

Is there any other info you can provide to rule out or confirm my guesses?

**Comment by gstratford** [comment]
@webzwo0i not super helpful, but here is the results when running "localStorage.debug = '*';  on a pad/console displaying the error...
<img width="882" alt="Screen Shot 2021-01-06 at 11 13 38 AM" src="https://user-images.githubusercontent.com/2601521/103810528-4018d480-5010-11eb-81c8-446cc625833a.png">

**Comment by webzwo0i** [comment]
Sorry I wasn't very clear. You need to set `localStorage.debug = '*'` and then reload the pad, let the console open. Then you should see a lot of engine.io/socket.io debug output. Leave it open like that for the night and in case the error happens, you can right-click and "save as". Because you probably don't want to share all the details, search for error/TransportError and the lines above the error message are probably most relevant.

After that you can `delete localStorage.debug` to remove the debug logging.

For instance:
```
index.js:83 engine.io-client:socket writing ping packet - expecting pong within 5000ms +21s
index.js:83 engine.io-client:socket flushing 1 packets in socket +1ms
index.js:83 engine.io-client:socket socket close with reason: "ping timeout" +5s
index.js:83 socket.io-client:manager onclose +26s
index.js:83 socket.io-client:manager cleanup +2ms
index.js:83 socket.io-client:socket close (ping timeout) +26s
index.js:83 socket.io-client:socket close (ping timeout) +1ms
index.js:83 socket.io-client:manager will wait 1488ms before reconnect attempt +5ms
index.js:83 socket.io-client:manager attempting reconnect +1s
index.js:83 socket.io-client:manager readyState closed +27ms
index.js:83 socket.io-client:manager opening https://XX:443/ +0ms
index.js:83 engine.io-client:socket creating transport "polling" +2s
index.js:83 engine.io-client:polling polling +31s
index.js:83 engine.io-client:polling-xhr xhr poll +31s
index.js:83 engine.io-client:polling-xhr xhr open GET: https://XX/socket.io/?EIO=3&transport=polling&t=NRPhoAf +1ms
index.js:83 engine.io-client:polling-xhr xhr data null +0ms
index.js:83 engine.io-client:socket setting transport polling +4ms
index.js:83 socket.io-client:manager connect attempt will timeout after 20000 +6ms
index.js:83 engine.io-client:socket socket error {"type":"TransportError","description":0} +50ms
index.js:83 socket.io-client:manager connect_error +49ms
index.js:83 socket.io-client:manager cleanup +1ms
index.js:83 socket.io-client:manager reconnect attempt error +1ms
index.js:83 socket.io-client:manager will wait 2993ms before reconnect attempt +0ms
index.js:83 engine.io-client:socket socket close with reason: "transport error" +3ms
index.js:83 engine.io-client:polling transport not open - deferring close +56ms
```
The above happened, when I disable my network connection. After it did not receive "pong", it tries reconnect. I just pasted the first lines, but it continues to try reconnecting 5 times and then gives up.

There's no easy way to remove all "privacy" related stuff. The "t=" token is not important, but you should remove any occurrence of "sid" which is the (private) session id. If that's not possible you could also send me the file via PGP mail

**Comment by pjvandehaar** [comment]
Here's my server logs for the same error on `1.8.7` on current `master` (01a76):

```
Jan 27 22:50:41 node[711]: [2021-01-28 03:50:41.474] [WARN] client - Error: socket.io connection error: {"type":"TransportError","description":{"isTrusted":true}} -- { errorId: 'pmJkb9QxJSbYNNgyFuMQ',
Jan 27 22:50:41 node[711]:   type: 'Uncaught exception',
Jan 27 22:50:41 node[711]:   msg:
Jan 27 22:50:41 node[711]:    'Error: socket.io connection error: {"type":"TransportError","description":{"isTrusted":true}}',
Jan 27 22:50:41 node[711]:   url: 'https://e.example.com/p/2020-01-25_29',
Jan 27 22:50:41 node[711]:   source:
Jan 27 22:50:41 node[711]:    'https://e.example.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=021295d6',
Jan 27 22:50:41 node[711]:   linenumber: 278,
Jan 27 22:50:41 node[711]:   userAgent:
Jan 27 22:50:41 node[711]:    'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1',
Jan 27 22:50:41 node[711]:   stack:
Jan 27 22:50:41 node[711]:    'https://e.example.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=021295d6:278:20\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:6:19844\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:8:9139\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:6:22876\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:6:25658\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:8:12359\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:6:19844\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:7:5425\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:7:606\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:6:19844\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:7:14606\nhttps://e.example.com/socket.io/socket.io.js?v=021295d6:8:6647' }
```

For convenience, here's that last line with `\n`s as newlines:
```
https://e.example.com/socket.io/socket.io.js?v=021295d6:6:19844
https://e.example.com/socket.io/socket.io.js?v=021295d6:8:9139
https://e.example.com/socket.io/socket.io.js?v=021295d6:6:22876
https://e.example.com/socket.io/socket.io.js?v=021295d6:6:25658
https://e.example.com/socket.io/socket.io.js?v=021295d6:8:12359
https://e.example.com/socket.io/socket.io.js?v=021295d6:6:19844
https://e.example.com/socket.io/socket.io.js?v=021295d6:7:5425
https://e.example.com/socket.io/socket.io.js?v=021295d6:7:606
https://e.example.com/socket.io/socket.io.js?v=021295d6:6:19844
https://e.example.com/socket.io/socket.io.js?v=021295d6:7:14606
https://e.example.com/socket.io/socket.io.js?v=021295d6:8:6647'
```

**Comment by pjvandehaar** [comment]
Here are the logs you asked for:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/862089/106181265-617e6380-616b-11eb-8d05-0b5bc9531f49.png">
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/862089/106181344-7ce96e80-616b-11eb-85eb-b13479ae866f.png">

**Comment by fooness** [comment]
+1

Any news to this problem?

**Comment by rhansen** [comment]
Unfortunately the socket.io debug logs don't help much. It smells like a flaky network to me but I'm not sure, and I wouldn't expect that exception if that was the case. Would you try setting [`socketTransportProtocols`](https://github.com/ether/etherpad-lite/blob/294f2a251f15df7dea7b4f50328b0bd7775a4269/settings.json.template#L451) to `["websocket"]` and see if you can still reproduce?

**Comment by pjvandehaar** [comment]
Yeah, it still happens with just `["websocket"]`, and yeah, my wifi drops a lot.
