### ISSUE TITLE
Best method to update Settings?

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4785]
https://github.com/citizenos/ep_image_upload/blob/master/settings.js isn't working as I expected it would..

Any ideas for best method/approach without modifying ``settings.json``?

**Comment by webzwo0i** [comment]
It's setting it as settings.maxHttp... but it should be settings.socketio.maxHtt... ?

Also, in https://github.com/ether/etherpad-lite/pull/4781 I noticed that settings are not reloaded during plugin install/uninstall. I fixed it in that PR. When I add debug statements in that branch and install ep_image_upload via /admin I can see that the maxHttp... setting has been set. However, when I remove the plugin again, I see that the maxHttp... setting is still present. I suspect it is not removed, because it is a custom setting that etherpad does not know about. So I think your issue is resolved with my PR, but we should open another issue for removing (custom) settings from plugins when the plugin is removed.

```
diff --git a/src/static/js/pluginfw/installer.js b/src/static/js/pluginfw/installer.js
index 7f03a01d..125e687a 100644
--- a/src/static/js/pluginfw/installer.js
+++ b/src/static/js/pluginfw/installer.js
@@ -17,8 +17,11 @@ const loadNpm = async () => {
 };
 
 const onAllTasksFinished = async () => {
+  console.warn("settings1",settings)
   settings.reloadSettings();
+  console.warn("settings2",settings)
   await hooks.aCallAll('loadSettings', {settings});
+  console.warn("settings3",settings)
   await hooks.aCallAll('restartServer');
 };
```

**Comment by JohnMcLear** [comment]
oh yeah the endpoint moved in rhansen change! :D lol



-----Original message-----

**Comment by JohnMcLear** [comment]
tnx for spotting btw, I think it should be okay now
