### ISSUE TITLE
1.8.13: page load broken with `'self'` content security policy (Ace2Editor.init() error event while waiting for load event)

### ISSUE THREAD

**Issue by dvzrv** [ether/etherpad-lite#4975]
**Describe the bug**
After updating from 1.8.12 to 1.8.13 (no plugins, plain packaged version that I provide in the AUR), I get the following on loading any pad:

```
An error occurred

Please press and hold Ctrl and press F5 to reload this page

If the problem persists, please send this error message to your webmaster:
ErrorId: Hlk02KxskYcOry455748
Unhandled Promise rejection
URL: https://my-pad.tld/p/test
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
Ace2Editor.init() error event while waiting for load event
at https://my-pad.tld/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=580f7db7 at line 49
```

Reloading the page doe not fix the issue.

**To Reproduce**
1. Go to any pad
2. See error

**Expected behavior**
pad loads normally

**Screenshots**
![screenshot-2021-03-25_20-28-38_blur](https://user-images.githubusercontent.com/432519/112532932-b1635a80-8da9-11eb-8da5-233300bfe9ed.png)

**Server (please complete the following information):**
 - Etherpad version: 1.8.13
 - OS: Arch Linux
 - Node.js version (`node --version`): v15.12.0
 - npm version (`npm --version`): 7.7.4

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 87.0

**Smartphone (please complete the following information):**

**Additional context**
Downgrading to 1.8.12 fixes the issue.

The PKGBUILD that creates the package can be found here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=etherpad-lite

**Comment by webzwo0i** [comment]
works for me on ff 87.0/node 15.12.0/npm 7.7.4

Do you see any other errors in developer console when this happens?

**Comment by flotho** [comment]
same issue with a reverse proxy and authenticatication in the proxy.
without the authentication in the proxy then it's working

**Comment by webzwo0i** [comment]
Interesting! Would be cool to get this fixed.
Can you provide steps to replicate? Do you mean https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authenticate ?

**Comment by flotho** [comment]
maybe related to https://github.com/ether/etherpad-lite/issues/4820

**Comment by flotho** [comment]
> same issue with a reverse proxy and authenticatication in the proxy.
> without the authentication in the proxy then it's working

my bad, failed with or without reverse proxy.

**Comment by webzwo0i** [comment]
I think we are on the right track. Might be due to https://github.com/ether/etherpad-lite/commit/1b8cd0747dc76b7a46f7e00201b2b73b1591e456

Can you post a list of your installed plugins+version please.

**Comment by larskasper** [comment]
Could it be that the server (a proxy server like nginx) is setting a **Content-Security-Policy header** (CSP)?

That can be checked in the server configuration, or in a web browser’s inspector/developer tools (in Firefox for example: _Tools_ → _Web Developer_ → _Web Console_, then expanding the _GET_ requests and looking for _Response Headers_; in that console you also see the errors if something is blocked by CSP), or in a tool like _curl_ (`curl -isS https://pad.example/p/test | grep -i content-security-policy`).

I noticed the mentioned error message and non-working pads with Etherpad Lite version 1.8.13 when in the proxying nginx a Content-Security-Policy was set. The error was gone when the Content-Security-Policy was not set (or a permissive one like `add_header Content-Security-Policy "default-src https: 'unsafe-eval' 'unsafe-inline'";` was set, which still blocks some content), or when Etherpad Lite version 1.8.12 was used (with a Content-Security-Policy).

**Comment by nuxi** [comment]
I just upgraded etherpad from 1.8.6 to 1.8.13 and hit this issue. 

Previously something like this worked just fine `default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' data:; connect-src 'self'; img-src 'self' https: data:; media-src 'self' https:; frame-src 'self'; frame-ancestors 'self'; form-action 'self'`

Now `'self'` no longer seems to match requests eventhough they are going to the same host, with the same port, and the same scheme. To get it working again I had to explicitly add the host to `default-src`, `script-src`, `style-src`, and `connect-src`. This shouldn't be necessary, `'self'` should have covered this case. I don't know why it suddenly isn't after an upgrade.

**Comment by nuxi** [comment]
I was able to bisect it, `'self'` worked in the CSP up until https://github.com/ether/etherpad-lite/commit/40448606

**Comment by rhansen** [comment]
Do all browsers behave the same? This looks like a browser bug to me, but I don't know enough about CSP to be sure.

**Comment by nuxi** [comment]
I see the problem in Firefox 89 and I do not see it in Chromium 90.

I'm just running 1.8.12 instead for now.

**Comment by webzwo0i** [comment]
Not a browser bug, but non-perfect spec, see https://github.com/w3c/webappsec-csp/issues/459 and https://bugzilla.mozilla.org/show_bug.cgi?id=1567970

:-(

**Comment by dvzrv** [comment]
I can confirm that adding the host to the CSP header explicitly "fixes" this. However, given that https://github.com/ether/etherpad-lite/commit/40448606 broke this, I'd appreciate this being fixed in etherpad, rather than waiting for mozilla to investigate this.

**Comment by rhansen** [comment]
Reverting commit 404486069c204cbec840aa802fc6a18dac013418 is not feasible, and it's unclear to me how to work around this in Firefox. If someone can figure out an approach that works I'd be happy to apply it.

**Comment by rhansen** [comment]
> Not a browser bug, but non-perfect spec, see w3c/webappsec-csp#459 and https://bugzilla.mozilla.org/show_bug.cgi?id=1567970

Those links are talking about an unrelated issue. (Those are regarding the meaning of "self" when used in a `<meta http-equiv="Content-Security-Policy" content="...">` tag in a child srcdoc iframe.)

I did some more digging and to me [the standard](https://www.w3.org/TR/CSP2/#processing-model-iframe-srcdoc) is clear on this topic:

> Whenever a user agent creates an `iframe` `srcdoc` document in a browsing context nested in the protected resource, if the user agent is enforcing any policies for the protected resource, the user agent MUST enforce those policies on the `iframe` `srcdoc` document as well.

So I really think this is a Firefox bug, not a flaw in the standard. I couldn't find it reported anywhere so I did some more investigation and this bug only happens when you have nested srcdoc iframes (`<iframe srcdoc="...">` inside another `<iframe srcdoc="...">`). I suspect that not many applications have nested iframes like this, which is probably why I couldn't find any existing reports. I filed a new bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1721296

**Comment by webzwo0i** [comment]
I really appreciate the effort @rhansen!
The part of the spec you cited seems to be clear and iirc I also saw it failing on the inner, not the outer iframe. I found https://wpt.fyi/results/content-security-policy/meta/sandbox-iframe.html?label=experimental&label=master&aligned which seem to fail the same way we saw here (although it's meta tag + img-src and sandbox)

In [CSP3 draft](https://w3c.github.io/webappsec-csp/#initialize-document-csp) the cited paragraph doesn't appear anymore and there is a "Note: This is needed to facilitate the 'self' checks of local scheme documents/workers that have inherited their policy but have an opaque origin. Most of the time this will simply be the environment settings object’s origin." - our inner iframe has an opaque origin (srcdoc) and has inherited it's policy (from the outer iframe where it was dynamically generated), but not sure it is a "local scheme document".
Also "Note: We compare against the fallback base URL in order to deal correctly with things like an iframe srcdoc Document which has been sandboxed into an opaque origin." (we don't use sandbox or explicit base hrefs, though)

Because of this I thought CSP3 is way more clear than CSP2 (although the above paragraphs might not apply to our use case), then I found https://github.com/antosart/policy-container-explained which I probably misinterpreted (it seems to talk about unifying the different approaches to inheritance across all the various policies out there).

Indeed I run the tests with meta tags - ignoring that policies won't be enforced to anything above the meta tag. Besides that my understanding is that it shouldn't make a difference if CSP is applied via header or meta?!

So thanks again for filling the bug report and let's see if we get some insights from mozilla. @dvzrv Is anything blocking you from not using self? Maybe we can add some other code that helps setting a correct header not using "self"? It was a bigger effort to get to where we are now regarding page load, so reverting the commit is not an option imo.

@rhansen Just in case: What do you think, if we'd try to remove iframes entirely from Etherpad? There was a PoC PR some time ago. IMO, this would be a clever step for the future, but I'm not sure if it'll break anything badly.

**Comment by webzwo0i** [comment]
It's getting even weirder: (After adding require-kernel/ace2inner/ace2common to script tags instead dynamically adding from parent) Adding any or both of innerFrame.csp and outerFrame.csp with a value of `script-src 'self'` fails in Chromium, too (Firefox does not support csp attributes of iframes yet).

Adding `<meta http-equiv="Content-Security-Policy" content="script-src ip:port">` to the inner iframe's head element when setting srcdoc will make it work in Chromium, as does `script-src 'self'`. So what's the difference setting this via csp attribute or meta element?

**Comment by webzwo0i** [comment]
@rhansen If you'd accept something like https://github.com/ether/etherpad-lite/pull/5124 (probably with relative links) I can add some more templating, so that it would reduce the amount of script/style injections etc in ace.js. I expect a large amount of code in ace.js to become obsolete after doing this.

At least this seems to fix the CSP issue, as it works with `self` now, provided the corresponding headers are set when serving aceInner/aceOuter (probably also works when only sending the headers with pad.html - I didn't test this)

I must admit, I don't remember why we used `srcdoc` in the first place

**Comment by webzwo0i** [comment]
@dvzrv Just for completeness, can you test if #5124 fixes the problem for you?

**Comment by rhansen** [comment]
> Our inner iframe has an opaque origin (srcdoc)

The CSP3 draft is difficult to read, but I think it's more subtle than that.

The [location](https://developer.mozilla.org/en-US/docs/Web/API/Window/location) for srcdoc iframes is a URL with a [local scheme](https://fetch.spec.whatwg.org/#local-scheme) ([`about:srcdoc`](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#about%3Asrcdoc)). A URL's origin is [opaque if it has a local scheme](https://url.spec.whatwg.org/#concept-url-origin). However, if I understand correctly, [srcdoc iframes get a copy of their parent's policy](https://w3c.github.io/webappsec-csp/#security-inherit-csp), so `'self'` checks in srcdoc iframes should be against [the origin used](https://w3c.github.io/webappsec-csp/#policy-self-origin) by the parent (which is not opaque), not the srcdoc iframe's origin (which is opaque). (If the srcdoc iframes were [sandboxed](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) then the `'self'` checks would be against an opaque origin.)

(I'm far from an expert on this topic, so my understanding of the spec could be wrong.)

> What do you think, if we'd try to remove iframes entirely from Etherpad?

In the long run I think it would result in better code, but I think it would take a considerable amount of effort. In particular, we would need to figure out a way to migrate plugins ([example](https://github.com/ether/ep_webrtc/blob/3d81cdd47740847374df637804733ec6a4a55003/static/js/index.js#L398-L399)).

> So what's the difference setting this via csp attribute or meta element?

Setting CSP in a srcdoc iframe's meta tag is the topic of the bugs you originally linked. In other words, the standard is not clear. (If you set the CSP in the meta tags for the top-level frame (`src/templates/pad.html`) then it should behave as expected.)

> @rhansen If you'd accept something like #5124 (probably with relative links) I can add some more templating, so that it would reduce the amount of script/style injections etc in ace.js. I expect a large amount of code in ace.js to become obsolete after doing this.

I like the approach in PR #5124. For the first iteration I would prefer to serve empty HTML and leave the code in `ace.js` mostly untouched (only change `srcdoc='<!DOCTYPE html>'` to `src='../_empty.html'`). In a later PR we can convert the `ace.js` iframe element creation code into served HTML.

**Comment by dessalines** [comment]
This is also happening with the newest version of etherpad.

**Comment by SamTV12345** [comment]
So as an Option? As far as I can see this can imply security issues with XSS. I'll have a look how to implement that.

**Comment by dessalines** [comment]
Yep, that'd be best. Only add the CSP headers if `DISABLE_CSP=false` , which could be the default.

**Comment by SamTV12345** [comment]
Alright. I'll try that. If it's simply another header being conditionally added it should not be too hard.

**Comment by dessalines** [comment]
Whoa, I waited a few hours and the issue cleared up. Not even restarting my machines, or reinstalling etherpad worked at first. Sorry about that yall. 

It probably had to do with not enabling `TRUST_PROXY`, then some weird system-caching.

**Comment by SamTV12345** [comment]
Great that this is resolved now
