### ISSUE TITLE
Document how to migrate pads between etherpads

### ISSUE THREAD

**Issue by rgarrigue** [ether/etherpad-lite#5009]
* * *

name: Feature request
about: Suggest an idea for this project
title: 'Document how to migrate pads between etherpads'
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**

We're moving from an old etherpad to a new one

**Describe the solution you'd like**

A bunch of command to be c/c'ed in a terminal

**Describe alternatives you've considered**

I looked in the issues & wiki & documentation, couldn't find a "export" or "dump" or "migrate" making sense

**Comment by webzwo0i** [comment]
Some thoughts:
Etherpad is moving fast, so it is easy to miss some versions in between. On instances I maintain I have made several "big jumps" in the last years without doing anything special and actually this works pretty well. (However, I don't use a lot of different plugins or do a lot of installing/deleting experimental plugins.) The single most important mistake that you can make is setting a wrong database encoding. That happened a lot and we now have clear warnings during start up to prevent this from happening. In a lot of those cases the timeslider will be broken at some point, but normal pad operation continues.

In general, have your backups up to date at an safe place and know that you can make everything work from those backups. Use some kind of staging area/second domain so that people can test the new environment and copy the database over to this new environment, so in case anything is breaks, it would affect your production system.

There are scripts in ./bin that can help with different problems, but some of them might not work or need some work to be better. You should do a backup before running those.

Etherpad uses an extremely simple database schema, that makes it easy to restore parts of the data. During start or after an upgrade Etherpad does not change or migrate any data. This has the downside that there can be cases were a broken value stays in the database (e.g. a chat entry without author information). In general, we work around this in the code, make sure that future versions store correct data and that we can handle the "broken" data. But we don't delete it and reinsert the correct value. In most cases this is due to the fact, that we can't predict the correct data. E.g. when you have used a suboptimal encoding in the past and people used emojis (or any other glyph that has no representation with this encoding) on a pad and the database was not able to correctly store them, we have no way to reconstruct the correct glyph. (Actually, in this special case, we don't do anything about it in Etherpad's core code and you would need to repair the rows manually depending on the exact configuration that was applied. In most cases it's a matter of adding some "?" at specific points. This is something that can be automated, but as far as I know it hasn't been yet.)

Etherpad does not provide any database backup strategy and you can take the old database with you after upgrade. (Again, do a working backup first!)

I usually upgrade instances by doing something like:
```
rm -rf node_modules; git checkout node_modules/ep_etherpad-lite (there is a symlink in ./node_modules)
rm -rf src/node_modules;
./bin/installDeps.sh or cd src && npm i
reinstalling all plugins I want to use with npm i or via /admin interface after restart
```

You would need to check the changelog, or better, settings.json.template for changes in the settings since your version. As said, we can automate more to ensure our database is clean and no stale or broken entries are in there. If I'd need to do this, I would probably pick up one of the "check*" scripts in ./bin, compare all the stored atexts with the atexts that I generate from all the single changesets, check the contents of all other entries in the database (e.g. the padIds property of globalAuthors or said chat entries).

Also, recently, the problem has not been debugged entirely, but the asumption is that people have been using a plugin (ep_image_upload) with the option to put the image directly into the pad (as an attribute, just like bold or lists are attributes). Later they were using a setting to store the images in the cloud and link to them from the pads. Now, in a recent versions, we store those attributes more often in the database (which is better for recovering data), but this means that image data is now also stored possibly hundreds of times.
This example illustrates that using plugins can have an impact.

**Comment by muzzol** [comment]
`cp /path/to/old/etherpad/var/etherpad_sqlite.db /path/to/new/etherpad/var/etherpad_sqlite.db
`


edit **/path/to/new/etherpad/settings.json** and add/modify

```
  "dbType" : "sqlite",
  "dbSettings" : {
                   "filename" : "var/etherpad_sqlite.db"
                 },
```

that's really all you need to do. a plugin like [adminpads2](https://npmjs.org/package/ep_adminpads2) comes handy here, but not really needed.
