### ISSUE TITLE
Should etherpad import remove revisions?

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5155]
Suppose you have a pad with 100 revisions and you import an etherpad file that has only 50 revisions. The revisions 51 up to 100 while be kept in the database.

Nothing bad happens when exporting such a pad again to .etherpad format, because it will take the head revision number (50) and only include changesets up to that revision. However, I feel like we should remove any left revisions/comments/chat entries from the old pad, before importing the new data.

**Comment by rhansen** [comment]
My guy instinct is to add a new rev 101 that empties the pad, then play out the 50 revs on top of that.

**Comment by JohnMcLear** [comment]
I'm with @rhansen on that.  

If you remove history it leaves a huge opportunity for abuse/manipulation and would destroy one of Etherpad's core philosophies of accuracy of document fidelity (required for International law matters).

So I'd say this is intentional design.

**If you truly want to modify the history of a pad, only the admin has such powers.**  A user should never be able to remove history.
