### ISSUE TITLE
Try Out Links in Documentation and NPM 

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5216]
**All Try Out LInks** on https://github.com/ether/etherpad-lite#installation **lead to a 502 Error** - I suggest to fix that
![Screen Shot 2021-10-03 at 08 20 17](https://user-images.githubusercontent.com/1982011/135736266-3baa93c1-0a10-47d4-b703-0a7e44252890.png)

**A similar/same problem exists on each plugin page's Try Out Link  at NPM** - as an example
There is no way to test out a plugin before installation on NPM or with the links in the documentation!
Either delete those links (as they would be useless when not working - or fixing would be advised)
![Screen Shot 2021-10-03 at 08 24 08](https://user-images.githubusercontent.com/1982011/135736263-8bc7f99f-0bc0-409e-b133-08cee42f9b45.png)

**Comment by JohnMcLear** [comment]
I bumped @rhansen about this yesterday.  They should be up and I wanted to know if they are down intentionally.

For some reason uptimerobot is showing them as 400 not 502...

**Comment by JohnMcLear** [comment]
IDK why uptimerobot was weird but whatever.

For some reason the Etherpad instances weren't restarting on system restart.  I enabled via systemctl and started manually and everything is back up.

Not ideal but hopefully resolved now!

I did however drop analysis.etherpad.com because it has an error and I don't have time to dive into that now.

**Comment by JohnMcLear** [comment]
Just for posterity, the reason some instances were failing is because we have so many demo instances on that box it was maxing out MySQL connections :P  I upped allowable # of connections and it brought all instances up.
