### ISSUE TITLE
Etherpad is not working when serving from same domain of my website

### ISSUE THREAD

**Issue by Nehasoni988** [ether/etherpad-lite#5421]
I want to embed etherpad at some places at my site. So, I installed the etherpad at the same server where I already deployed my website built in vuejs.

(I am using Nginx) 

My project setup structure is like this 

- var
  - www
     - html
       - my_website
       - etherpad
  
I am trying to serve both my_website and etherpad through the same domain, so I configure my conf file like this-
https://gist.github.com/Nehasoni988/2b84f9676e80f72a7da87517802c5410

when I am trying to access the path https://domain_name/p/{pad_id}, it is giving me a page like this with these errors-

![Screenshot from 2022-02-18 12-59-39](https://user-images.githubusercontent.com/33506558/154637865-cde267bf-762f-4206-b348-c3e65b6b18d4.png)

If I serve etherpad at the primary domain then it works fine but I want to serve my website on the primary domain and serve etherpad only when requested with `domain_name/p`.

**Comment by Nehasoni988** [comment]
It worked.
Thanks!

**Comment by Nehasoni988** [comment]
Hello,

I installed a few plugins at my local host.
Now, I deployed the code to the remote server and run installDeps.sh script.
But localhost installed plugins are not available at my remote server.

I checked that installed plugins are registered in package-lock.json of the root folder which lies in .gitignore.
Should I remove package-lock.json from .gitignore ? Else how can I deploy installed plugins to a remote server?

@ziegenberg

**Comment by ziegenberg** [comment]
Why is .gitignore a folder? It should be a file. For the documentation what .gitignore does and how it works please read the following: https://git-scm.com/docs/gitignore

**Comment by ziegenberg** [comment]
Why not install plugins on the remote host the same way you installed them on the localhost?

**Comment by Nehasoni988** [comment]
> Why not install plugins on the remote host the same way you installed them on the local host?

In this way, I always need to take care of what I installed on local should be installed on remote too.
I want if there is any way which can register all plugins in a package.json file and when I deploy the code and run the install dependencies script, all the plugins in package.json should install at remote too. Like it happens in the projects when we add a new packgae.

**Comment by webzwo0i** [comment]
If you copy the whole directory you probably don't need to run installDeps. Or do you mean you used git remotes and some files are ignored?
Also note that we do have two package-locks for different reasons. The one in ./src is used in installDeps and is part of the releases. The one in your main directory contains all installed plugins and their dependencies. So you need to run `npm i` in your main directory, too. It can happen that npm hoist dependencies when running npm in the main directory, ie a dependency moves from ./src/node_modules to ./node_modules. (This is due to our design, ie plugins are in ./node_modules and a special symlink that points from ./node_modules/ep_etherpad-lite to ./src, too.)

So depending on the npm version you use, it's possible that the directories are different between two installations.

**Comment by Nehasoni988** [comment]
I think I need to install the packages manually as I did at local because it is defined in that way in package files.
Thanks for your answers.

I have one more question-

When "requireAuthentication" is true, and someone wants to access any pad, then a sign-in popup prompts for username and password.
Can you tell me where is the code of this sign-in prompt? I want to customize this popup.

Thanks n advance.
