### ISSUE TITLE
Libraries not found (bin/installDeps.sh)

### ISSUE THREAD

**Issue by lucaguindani** [ether/etherpad-lite#5873]
Last time I tried to update etherpad I got some warnings (libraries not found) while installing dependencies. We can see exactly the same behavior in github actions.

https://github.com/ether/etherpad-lite/actions/runs/5836503637/job/15830215065#step:5:17
https://github.com/ether/etherpad-lite/actions/runs/5836503637/job/15830215065#step:5:47

 - Etherpad version: 1.9.1
 - OS: Ubuntu 22.04
 - Node.js version (`node --version`): 18.16.1
 - npm version (`npm --version`): 9.5.1
 - Is the server free of plugins: headings2

Looks like the instance is working fine anyway but can we just ignore theses warnings ? Is it safe for production ?

Many thanks.

**Comment by SamTV12345** [comment]
Hi,
thanks for creating an issue. You don't need to worry about this. That is because we include elasticsearch like this:
"elasticsearch8": "npm:@elastic/elasticsearch@^8.8.1",
which forces the elasticsearch package to be retrieved from npm. It is just a false positive. The driver is still downloaded. Once #5812 is merged that message should hopefully disappear. 

So in summary it should be not a problem and is safe to use in production. 

If you find a bug during upgrade feel free to create an issue.

**Comment by lucaguindani** [comment]
Thanks for the quick answer @SamTV12345. I'll close the issue since there is nothing more to do :)
