### ISSUE TITLE
List all pads

### ISSUE THREAD

**Issue by bartounet16** [ether/etherpad-lite#697]
Hello 
i am interesting to show a list about all pads...

How can i do that ? API permit that ?

Mysql select can do that ?

How delete documents ?

**Comment by dcht00** [comment]
Since this thread is on top of search results — here's how to currently do this:

https://etherpad.org/doc/v2.2.5/index.html#_listallpads

-------

In practice:

`$ curl "https://YOUR_INSTANCE/api/1.3.0/listAllPads?apikey=YOURKEY"
`

If you're still using
`  "authenticationMethod": "${AUTHENTICATION_METHOD:apikey}",
`
The key is in APIKEY.txt. For tokens it's a bit different ;)
