### ISSUE TITLE
Question: Base URL setting?

### ISSUE THREAD

**Issue by jcharaoui** [ether/etherpad-lite#71]
From the README example it seems possible to run Etherpad under a different base URL than " / ". I'd like to run it under "mydomain.com/pad". Is there a setting somewhere for that? Or modifications to the code? Thanks.

**Comment by massih10** [comment]
Can someone help me with this using the Docker File on Kubernetes using an ingress rule? I cant get it to work on a relative path https://<somedomain>/etherpad. It's looking for all static files under https://<somedomain>/ . The base path under https://<somedomain>/ is already used by another application which is why I m not sure how to use the methods in this [post](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy).

**Comment by rhansen** [comment]
Discussed in #5134.
